// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "LatticeBasedMigrationRule3.pypp.hpp"

namespace bp = boost::python;

struct LatticeBasedMigrationRule_less__3__greater__wrapper : LatticeBasedMigrationRule< 3 >, bp::wrapper< LatticeBasedMigrationRule< 3 > > {

    LatticeBasedMigrationRule_less__3__greater__wrapper(LatticeBasedMigrationRule<3> const & arg )
    : LatticeBasedMigrationRule<3>( arg )
      , bp::wrapper< LatticeBasedMigrationRule< 3 > >(){
        // copy constructor
        
    }

    LatticeBasedMigrationRule_less__3__greater__wrapper( )
    : LatticeBasedMigrationRule<3>( )
      , bp::wrapper< LatticeBasedMigrationRule< 3 > >(){
        // null constructor
    
    }

    virtual ::std::vector< int > GetIndices( ::std::vector< boost::shared_ptr<VesselNode<3> > > const & rNodes ) {
        if( bp::override func_GetIndices = this->get_override( "GetIndices" ) )
            return func_GetIndices( boost::ref(rNodes) );
        else{
            return this->LatticeBasedMigrationRule< 3 >::GetIndices( boost::ref(rNodes) );
        }
    }
    
    ::std::vector< int > default_GetIndices( ::std::vector< boost::shared_ptr<VesselNode<3> > > const & rNodes ) {
        return LatticeBasedMigrationRule< 3 >::GetIndices( boost::ref(rNodes) );
    }

    virtual int GetNeighbourMovementIndex( ::std::vector< double > movementProbabilities, ::std::vector< unsigned int > neighbourIndices ){
        if( bp::override func_GetNeighbourMovementIndex = this->get_override( "GetNeighbourMovementIndex" ) )
            return func_GetNeighbourMovementIndex( movementProbabilities, neighbourIndices );
        else{
            return this->LatticeBasedMigrationRule< 3 >::GetNeighbourMovementIndex( movementProbabilities, neighbourIndices );
        }
    }
    
    virtual int default_GetNeighbourMovementIndex( ::std::vector< double > movementProbabilities, ::std::vector< unsigned int > neighbourIndices ){
        return LatticeBasedMigrationRule< 3 >::GetNeighbourMovementIndex( movementProbabilities, neighbourIndices );
    }

    virtual ::std::vector< double > GetNeighbourMovementProbabilities( ::boost::shared_ptr< VesselNode< 3 > > pNode, ::std::vector< unsigned int > neighbourIndices, unsigned int gridIndex ){
        if( bp::override func_GetNeighbourMovementProbabilities = this->get_override( "GetNeighbourMovementProbabilities" ) )
            return func_GetNeighbourMovementProbabilities( pNode, neighbourIndices, gridIndex );
        else{
            return this->LatticeBasedMigrationRule< 3 >::GetNeighbourMovementProbabilities( pNode, neighbourIndices, gridIndex );
        }
    }
    
    virtual ::std::vector< double > default_GetNeighbourMovementProbabilities( ::boost::shared_ptr< VesselNode< 3 > > pNode, ::std::vector< unsigned int > neighbourIndices, unsigned int gridIndex ){
        return LatticeBasedMigrationRule< 3 >::GetNeighbourMovementProbabilities( pNode, neighbourIndices, gridIndex );
    }

    virtual ::std::vector< DimensionalChastePoint<3> > GetDirections( ::std::vector< boost::shared_ptr<VesselNode<3> > > const & rNodes ) {
        if( bp::override func_GetDirections = this->get_override( "GetDirections" ) )
            return func_GetDirections( boost::ref(rNodes) );
        else{
            return this->AbstractMigrationRule< 3 >::GetDirections( boost::ref(rNodes) );
        }
    }
    
    ::std::vector< DimensionalChastePoint<3> > default_GetDirections( ::std::vector< boost::shared_ptr<VesselNode<3> > > const & rNodes ) {
        return AbstractMigrationRule< 3 >::GetDirections( boost::ref(rNodes) );
    }

};

void register_LatticeBasedMigrationRule3_class(){

    { //::LatticeBasedMigrationRule< 3 >
        typedef bp::class_< LatticeBasedMigrationRule_less__3__greater__wrapper, bp::bases< AbstractMigrationRule< 3 > > > LatticeBasedMigrationRule3_exposer_t;
        LatticeBasedMigrationRule3_exposer_t LatticeBasedMigrationRule3_exposer = LatticeBasedMigrationRule3_exposer_t( "LatticeBasedMigrationRule3", bp::init< >() );
        bp::scope LatticeBasedMigrationRule3_scope( LatticeBasedMigrationRule3_exposer );
        { //::LatticeBasedMigrationRule< 3 >::Create
        
            typedef LatticeBasedMigrationRule< 3 > exported_class_t;
            typedef ::boost::shared_ptr< LatticeBasedMigrationRule< 3 > > ( *Create_function_type )(  );
            
            LatticeBasedMigrationRule3_exposer.def( 
                "Create"
                , Create_function_type( &::LatticeBasedMigrationRule< 3 >::Create ) );
        
        }
        { //::LatticeBasedMigrationRule< 3 >::GetIndices
        
            typedef LatticeBasedMigrationRule< 3 > exported_class_t;
            typedef ::std::vector< int > ( exported_class_t::*GetIndices_function_type)( ::std::vector< boost::shared_ptr<VesselNode<3> > > const & ) ;
            typedef ::std::vector< int > ( LatticeBasedMigrationRule_less__3__greater__wrapper::*default_GetIndices_function_type)( ::std::vector< boost::shared_ptr<VesselNode<3> > > const & ) ;
            
            LatticeBasedMigrationRule3_exposer.def( 
                "GetIndices"
                , GetIndices_function_type(&::LatticeBasedMigrationRule< 3 >::GetIndices)
                , default_GetIndices_function_type(&LatticeBasedMigrationRule_less__3__greater__wrapper::default_GetIndices)
                , ( bp::arg("rNodes") ) );
        
        }
        { //::LatticeBasedMigrationRule< 3 >::GetNeighbourMovementIndex
        
            typedef LatticeBasedMigrationRule< 3 > exported_class_t;
            typedef int ( LatticeBasedMigrationRule_less__3__greater__wrapper::*GetNeighbourMovementIndex_function_type)( ::std::vector< double >,::std::vector< unsigned int > ) ;
            
            LatticeBasedMigrationRule3_exposer.def( 
                "GetNeighbourMovementIndex"
                , GetNeighbourMovementIndex_function_type( &LatticeBasedMigrationRule_less__3__greater__wrapper::default_GetNeighbourMovementIndex )
                , ( bp::arg("movementProbabilities"), bp::arg("neighbourIndices") ) );
        
        }
        { //::LatticeBasedMigrationRule< 3 >::GetNeighbourMovementProbabilities
        
            typedef LatticeBasedMigrationRule< 3 > exported_class_t;
            typedef ::std::vector< double > ( LatticeBasedMigrationRule_less__3__greater__wrapper::*GetNeighbourMovementProbabilities_function_type)( ::boost::shared_ptr< VesselNode< 3 > >,::std::vector< unsigned int >,unsigned int ) ;
            
            LatticeBasedMigrationRule3_exposer.def( 
                "GetNeighbourMovementProbabilities"
                , GetNeighbourMovementProbabilities_function_type( &LatticeBasedMigrationRule_less__3__greater__wrapper::default_GetNeighbourMovementProbabilities )
                , ( bp::arg("pNode"), bp::arg("neighbourIndices"), bp::arg("gridIndex") ) );
        
        }
        { //::LatticeBasedMigrationRule< 3 >::SetMovementProbability
        
            typedef LatticeBasedMigrationRule< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetMovementProbability_function_type)( double ) ;
            
            LatticeBasedMigrationRule3_exposer.def( 
                "SetMovementProbability"
                , SetMovementProbability_function_type( &::LatticeBasedMigrationRule< 3 >::SetMovementProbability )
                , ( bp::arg("movementProbability") ) );
        
        }
        { //::AbstractMigrationRule< 3 >::GetDirections
        
            typedef LatticeBasedMigrationRule< 3 > exported_class_t;
            typedef ::std::vector< DimensionalChastePoint<3> > ( exported_class_t::*GetDirections_function_type)( ::std::vector< boost::shared_ptr<VesselNode<3> > > const & ) ;
            typedef ::std::vector< DimensionalChastePoint<3> > ( LatticeBasedMigrationRule_less__3__greater__wrapper::*default_GetDirections_function_type)( ::std::vector< boost::shared_ptr<VesselNode<3> > > const & ) ;
            
            LatticeBasedMigrationRule3_exposer.def( 
                "GetDirections"
                , GetDirections_function_type(&::AbstractMigrationRule< 3 >::GetDirections)
                , default_GetDirections_function_type(&LatticeBasedMigrationRule_less__3__greater__wrapper::default_GetDirections)
                , ( bp::arg("rNodes") ) );
        
        }
        LatticeBasedMigrationRule3_exposer.staticmethod( "Create" );
        bp::register_ptr_to_python< boost::shared_ptr< LatticeBasedMigrationRule<3> > >();
        bp::implicitly_convertible< boost::shared_ptr< LatticeBasedMigrationRule< 3 > >, boost::shared_ptr< AbstractMigrationRule< 3 > > >();
        bp::implicitly_convertible< boost::shared_ptr< TipAttractionLatticeBasedMigrationRule< 3 > >, boost::shared_ptr< LatticeBasedMigrationRule< 3 > > >();
        bp::implicitly_convertible< boost::shared_ptr< CellPopulationMigrationRule< 3 > >, boost::shared_ptr< LatticeBasedMigrationRule< 3 > > >();
        bp::implicitly_convertible< boost::shared_ptr< Owen2011MigrationRule< 3 > >, boost::shared_ptr< LatticeBasedMigrationRule< 3 > > >();
    }

}
