#ifndef TipAttractionLatticeBasedMigrationRule2_hpp__pyplusplus_wrapper
#define TipAttractionLatticeBasedMigrationRule2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_TipAttractionLatticeBasedMigrationRule2_class(py::module &m);
#endif // TipAttractionLatticeBasedMigrationRule2_hpp__pyplusplus_wrapper
