#ifndef WallShearStressBasedRegressionSolver3_hpp__pyplusplus_wrapper
#define WallShearStressBasedRegressionSolver3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_WallShearStressBasedRegressionSolver3_class(py::module &m);
#endif // WallShearStressBasedRegressionSolver3_hpp__pyplusplus_wrapper
