#ifndef WallShearStressBasedRegressionSolver2_hpp__pyplusplus_wrapper
#define WallShearStressBasedRegressionSolver2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_WallShearStressBasedRegressionSolver2_class(py::module &m);
#endif // WallShearStressBasedRegressionSolver2_hpp__pyplusplus_wrapper
