#ifndef AbstractVesselNetworkComponent2_hpp__pyplusplus_wrapper
#define AbstractVesselNetworkComponent2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractVesselNetworkComponent2_class(py::module &m);
#endif // AbstractVesselNetworkComponent2_hpp__pyplusplus_wrapper
