#ifndef AbstractVesselNetworkComponentCellularProperties2_hpp__pyplusplus_wrapper
#define AbstractVesselNetworkComponentCellularProperties2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractVesselNetworkComponentCellularProperties2_class(py::module &m);
#endif // AbstractVesselNetworkComponentCellularProperties2_hpp__pyplusplus_wrapper
