#ifndef AbstractVesselNetworkComponentCellularProperties3_hpp__pyplusplus_wrapper
#define AbstractVesselNetworkComponentCellularProperties3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractVesselNetworkComponentCellularProperties3_class(py::module &m);
#endif // AbstractVesselNetworkComponentCellularProperties3_hpp__pyplusplus_wrapper
