#ifndef VesselNetworkGraphCalculator3_hpp__pyplusplus_wrapper
#define VesselNetworkGraphCalculator3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VesselNetworkGraphCalculator3_class(py::module &m);
#endif // VesselNetworkGraphCalculator3_hpp__pyplusplus_wrapper
