#ifndef VesselNetworkPropertyManager2_hpp__pyplusplus_wrapper
#define VesselNetworkPropertyManager2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_VesselNetworkPropertyManager2_class(py::module &m);
#endif // VesselNetworkPropertyManager2_hpp__pyplusplus_wrapper
