#ifndef VesselNetworkGraphCalculator2_hpp__pyplusplus_wrapper
#define VesselNetworkGraphCalculator2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_VesselNetworkGraphCalculator2_class(py::module &m);
#endif // VesselNetworkGraphCalculator2_hpp__pyplusplus_wrapper
