#ifndef VesselNetworkPropertyManager3_hpp__pyplusplus_wrapper
#define VesselNetworkPropertyManager3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_VesselNetworkPropertyManager3_class(py::module &m);
#endif // VesselNetworkPropertyManager3_hpp__pyplusplus_wrapper
