#ifndef VesselNetworkGeometryCalculator3_hpp__pyplusplus_wrapper
#define VesselNetworkGeometryCalculator3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_VesselNetworkGeometryCalculator3_class(py::module &m);
#endif // VesselNetworkGeometryCalculator3_hpp__pyplusplus_wrapper
