Chaste: Owen11CaBasedDivisionRule< SPACE_DIM > Class Template Reference
Owen11CaBasedDivisionRule< SPACE_DIM > Class Template Reference
#include <Owen11CaBasedDivisionRule.hpp>
Public Member Functions
Owen11CaBasedDivisionRule ()
virtual ~Owen11CaBasedDivisionRule ()
virtual bool IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > &rCellPopulation)
void SetVesselNetwork (boost::shared_ptr< VesselNetwork< SPACE_DIM > > pVesselNetwork)
void SetRegularGrid (boost::shared_ptr< RegularGrid< SPACE_DIM > > mpRegularGrid)
void SetReferenceLengthScale (units::quantity< unit::length > referenceLengthScale)
virtual unsigned CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > &rCellPopulation)
template<>
bool IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< 1 > &rCellPopulation)
template<>
unsigned CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< 1 > &rCellPopulation)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
boost::shared_ptr< VesselNetwork< SPACE_DIM > > mpVesselNetwork
boost::shared_ptr< RegularGrid< SPACE_DIM > > mpRegularGrid
units::quantity< unit::length > mReferenceLengthScale
unsigned mCancerCellCarryingCapacity
Friends
class boost::serialization::access
Detailed Description
template<unsigned SPACE_DIM>
class Owen11CaBasedDivisionRule< SPACE_DIM >
A division rule for CA-based cell populations to divide randomly into the available neighbours. If there are no spaces then the move is aborted.
Definition at line 55 of file Owen11CaBasedDivisionRule.hpp.
Constructor & Destructor Documentation
template<unsigned SPACE_DIM> Owen11CaBasedDivisionRule< SPACE_DIM >::Owen11CaBasedDivisionRule ()
Default constructor.
Definition at line 43 of file Owen11CaBasedDivisionRule.cpp.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::serialize().
template<unsigned SPACE_DIM> Owen11CaBasedDivisionRule< SPACE_DIM >::~Owen11CaBasedDivisionRule () virtual
Empty destructor.
Definition at line 53 of file Owen11CaBasedDivisionRule.cpp.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::serialize().
Member Function Documentation
template<unsigned SPACE_DIM> unsigned Owen11CaBasedDivisionRule< SPACE_DIM >::CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > & rCellPopulation) virtual
Return the index for the Daughter node. This method can be used to move cells out of the way as necessary.
Parameters
pNewCell The cell to new cell
pParentCell The parent cell
rCellPopulation The CA-based cell population
Returns
the node index for the daughter cell.
Definition at line 152 of file Owen11CaBasedDivisionRule.cpp.
References Owen11CaBasedDivisionRule< SPACE_DIM >::IsRoomToDivide(), Owen11CaBasedDivisionRule< SPACE_DIM >::mCancerCellCarryingCapacity, Owen11CaBasedDivisionRule< SPACE_DIM >::mpRegularGrid, and Owen11CaBasedDivisionRule< SPACE_DIM >::mpVesselNetwork.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::serialize().
template<> unsigned Owen11CaBasedDivisionRule< 1 >::CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< 1 > & rCellPopulation)
Specialization to allow used with 1D classes
Parameters
pNewCell the new cell
pParentCell the parent cell
rCellPopulation the cell population
Returns
the daughter node index
Definition at line 284 of file Owen11CaBasedDivisionRule.cpp.
template<unsigned SPACE_DIM> bool Owen11CaBasedDivisionRule< SPACE_DIM >::IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > & rCellPopulation) virtual
Return whether there is room to divide at all.
Parameters
pParentCell The cell to divide
rCellPopulation The CA-based cell population
Returns
if the site is available.
Definition at line 58 of file Owen11CaBasedDivisionRule.cpp.
References Owen11CaBasedDivisionRule< SPACE_DIM >::mCancerCellCarryingCapacity, Owen11CaBasedDivisionRule< SPACE_DIM >::mpRegularGrid, and Owen11CaBasedDivisionRule< SPACE_DIM >::mpVesselNetwork.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::CalculateDaughterNodeIndex(), and Owen11CaBasedDivisionRule< SPACE_DIM >::serialize().
template<> bool Owen11CaBasedDivisionRule< 1 >::IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< 1 > & rCellPopulation)
Specialization to allow used with 1D classes
Parameters
pParentCell the parent cell
rCellPopulation the cell population
Returns
is there room to divide
Definition at line 145 of file Owen11CaBasedDivisionRule.cpp.
template<unsigned SPACE_DIM> template<class Archive > void Owen11CaBasedDivisionRule< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 87 of file Owen11CaBasedDivisionRule.hpp.
References Owen11CaBasedDivisionRule< SPACE_DIM >::CalculateDaughterNodeIndex(), Owen11CaBasedDivisionRule< SPACE_DIM >::IsRoomToDivide(), Owen11CaBasedDivisionRule< SPACE_DIM >::Owen11CaBasedDivisionRule(), Owen11CaBasedDivisionRule< SPACE_DIM >::SetReferenceLengthScale(), Owen11CaBasedDivisionRule< SPACE_DIM >::SetRegularGrid(), Owen11CaBasedDivisionRule< SPACE_DIM >::SetVesselNetwork(), and Owen11CaBasedDivisionRule< SPACE_DIM >::~Owen11CaBasedDivisionRule().
template<unsigned SPACE_DIM> void Owen11CaBasedDivisionRule< SPACE_DIM >::SetReferenceLengthScale (units::quantity< unit::length > referenceLengthScale)
Set the reference length scale
Parameters
referenceLengthScale the reference length scale
Definition at line 299 of file Owen11CaBasedDivisionRule.cpp.
References Owen11CaBasedDivisionRule< SPACE_DIM >::mReferenceLengthScale.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::serialize().
template<unsigned SPACE_DIM> void Owen11CaBasedDivisionRule< SPACE_DIM >::SetRegularGrid (boost::shared_ptr< RegularGrid< SPACE_DIM > > mpRegularGrid)
Set the regular grid
Parameters
mpRegularGrid The regular grid
Definition at line 305 of file Owen11CaBasedDivisionRule.cpp.
References Owen11CaBasedDivisionRule< SPACE_DIM >::mpRegularGrid.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::serialize().
template<unsigned SPACE_DIM> void Owen11CaBasedDivisionRule< SPACE_DIM >::SetVesselNetwork (boost::shared_ptr< VesselNetwork< SPACE_DIM > > pVesselNetwork)
Set the vessel network
Parameters
pVesselNetwork The vessel network
Definition at line 293 of file Owen11CaBasedDivisionRule.cpp.
References Owen11CaBasedDivisionRule< SPACE_DIM >::mpVesselNetwork.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::serialize().
Member Data Documentation
template<unsigned SPACE_DIM> unsigned Owen11CaBasedDivisionRule< SPACE_DIM >::mCancerCellCarryingCapacity private
Cancer cell carrying capacity
Definition at line 77 of file Owen11CaBasedDivisionRule.hpp.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::CalculateDaughterNodeIndex(), and Owen11CaBasedDivisionRule< SPACE_DIM >::IsRoomToDivide().
template<unsigned SPACE_DIM> boost::shared_ptr<RegularGrid<SPACE_DIM> > Owen11CaBasedDivisionRule< SPACE_DIM >::mpRegularGrid private
Regular Grid
Definition at line 67 of file Owen11CaBasedDivisionRule.hpp.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::CalculateDaughterNodeIndex(), Owen11CaBasedDivisionRule< SPACE_DIM >::IsRoomToDivide(), and Owen11CaBasedDivisionRule< SPACE_DIM >::SetRegularGrid().
template<unsigned SPACE_DIM> boost::shared_ptr<VesselNetwork<SPACE_DIM> > Owen11CaBasedDivisionRule< SPACE_DIM >::mpVesselNetwork private
Vessel network
Definition at line 62 of file Owen11CaBasedDivisionRule.hpp.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::CalculateDaughterNodeIndex(), Owen11CaBasedDivisionRule< SPACE_DIM >::IsRoomToDivide(), and Owen11CaBasedDivisionRule< SPACE_DIM >::SetVesselNetwork().
template<unsigned SPACE_DIM> units::quantity<unit::length> Owen11CaBasedDivisionRule< SPACE_DIM >::mReferenceLengthScale private
Reference length scale
Definition at line 72 of file Owen11CaBasedDivisionRule.hpp.
Referenced by Owen11CaBasedDivisionRule< SPACE_DIM >::SetReferenceLengthScale().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/cell/Owen11CaBasedDivisionRule.hpp
projects/MicrovesselChaste/src/population/cell/Owen11CaBasedDivisionRule.cpp