Chaste: GeometryWriter Class Reference
GeometryWriter Class Reference
#include <GeometryWriter.hpp>
Public Member Functions
GeometryWriter ()
~GeometryWriter ()
void SetInput (vtkSmartPointer< vtkPolyData > pSurface)
void SetFileName (const std::string &rFileName)
void SetOutputFormat (GeometryFormat::Value format)
void Write ()
Static Public Member Functions
static boost::shared_ptr< GeometryWriter > Create ()
Private Attributes
vtkSmartPointer< vtkPolyData > mpInputGeometry
std::string mFilename
GeometryFormat::Value mFormat
Detailed Description
This class writes geometry information stored as vtk polydata to file in VTP or ascci STL format. For the latter it is assume that the geometry is triangulated.
Definition at line 62 of file GeometryWriter.hpp.
Constructor & Destructor Documentation
GeometryWriter::GeometryWriter ()
Constructor
Definition at line 53 of file GeometryWriter.cpp.
GeometryWriter::~GeometryWriter ()
Destructor
Definition at line 61 of file GeometryWriter.cpp.
Member Function Documentation
boost::shared_ptr< GeometryWriter > GeometryWriter::Create () static
Construct a new instance of the class and return a shared pointer to it.
Returns
a shared pointer to the class
Definition at line 66 of file GeometryWriter.cpp.
void GeometryWriter::SetFileName (const std::string & rFileName)
Set the output filename, without extension
Parameters
rFileName the full output path without extension
Definition at line 72 of file GeometryWriter.cpp.
References mFilename.
Referenced by Part< DIM >::Write(), and GreensFunctionSolver< DIM >::WriteSolution().
void GeometryWriter::SetInput (vtkSmartPointer< vtkPolyData > pSurface)
Set the geometry to be written in vtk format
Parameters
pSurface the geometry to be written
Definition at line 77 of file GeometryWriter.cpp.
References mpInputGeometry.
Referenced by Part< DIM >::Write(), and GreensFunctionSolver< DIM >::WriteSolution().
void GeometryWriter::SetOutputFormat (GeometryFormat::Value format)
Set the output format, VTP or STL
Parameters
format the output format, VTP or STL
Definition at line 82 of file GeometryWriter.cpp.
References mFormat.
Referenced by Part< DIM >::Write().
void GeometryWriter::Write ()
Do the write
Definition at line 87 of file GeometryWriter.cpp.
References mFilename, mFormat, and mpInputGeometry.
Referenced by Part< DIM >::Write(), and GreensFunctionSolver< DIM >::WriteSolution().
Member Data Documentation
std::string GeometryWriter::mFilename private
The output file name
Definition at line 75 of file GeometryWriter.hpp.
Referenced by SetFileName(), and Write().
GeometryFormat::Value GeometryWriter::mFormat private
The output format
Definition at line 80 of file GeometryWriter.hpp.
Referenced by SetOutputFormat(), and Write().
vtkSmartPointer<vtkPolyData> GeometryWriter::mpInputGeometry private
The geometry to be written
Definition at line 70 of file GeometryWriter.hpp.
Referenced by SetInput(), and Write().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/geometry/writers/GeometryWriter.hpp
projects/MicrovesselChaste/src/geometry/writers/GeometryWriter.cpp