Chaste: MappableGridGenerator Class Reference
MappableGridGenerator Class Reference
#include <MappableGridGenerator.hpp>
Public Member Functions
MappableGridGenerator ()
~MappableGridGenerator ()
boost::shared_ptr< Part< 3 > > GeneratePlane (unsigned numX, unsigned numY, bool withEndCaps=true)
boost::shared_ptr< Part< 3 > > GenerateCylinder (double cylinderRadius, double cylinderThickness, double cylinderHeight, unsigned numX, unsigned numY, double cylinderAngle=2.0 *M_PI)
boost::shared_ptr< Part< 3 > > GenerateHemisphere (double sphereRadius, double sphereThickness, unsigned numX, unsigned numY, double sphereAzimuthAngle=2.0 *M_PI, double spherePolarAngle=0.5 *M_PI)
Private Attributes
units::quantity< unit::length > mReferenceLength
Detailed Description
Generate a part consisting of a grid of unit rectangles or cuboids. It is useful for mapping onto more complex geometries for subsequent meshing. 3-D only.
Definition at line 46 of file MappableGridGenerator.hpp.
Constructor & Destructor Documentation
MappableGridGenerator::MappableGridGenerator ()
Constructor
Definition at line 44 of file MappableGridGenerator.cpp.
MappableGridGenerator::~MappableGridGenerator ()
Destructor
Definition at line 49 of file MappableGridGenerator.cpp.
Member Function Documentation
boost::shared_ptr< Part< 3 > > MappableGridGenerator::GenerateCylinder (double cylinderRadius, double cylinderThickness, double cylinderHeight, unsigned numX, unsigned numY, double cylinderAngle = 2.0 * M_PI)
Generate a cylindrical grid, where the planar grid is mapped on to a cylinder of specified dimensions.
Parameters
cylinderRadius radius of the cylinder
cylinderThickness thickness of the cylinder
cylinderAngle sweep angle of the cylinder (radians)
cylinderHeight height of the cylinder
numX number of blocks around the cylinder circumference
numY number of blocks over the cylinder height
Returns
pointer to a Part representation of the cylinder
Definition at line 203 of file MappableGridGenerator.cpp.
References GeneratePlane(), and mReferenceLength.
boost::shared_ptr< Part< 3 > > MappableGridGenerator::GenerateHemisphere (double sphereRadius, double sphereThickness, unsigned numX, unsigned numY, double sphereAzimuthAngle = 2.0 * M_PI, double spherePolarAngle = 0.5 * M_PI)
Generate a hemispherical grid, where the planar grid is mapped on to a sphere of specified dimensions.
Parameters
sphereRadius radius of the sphere
sphereThickness thickness of the cylinder
sphereAzimuthAngle azimuth angle of the hemisphere (radians)
spherePolarAngle polar angle of the hemisphere (radians)
numX number of blocks around the cylinder circumference
numY number of blocks over the cylinder height
Returns
pointer to a Part representation of the hemisphere
Definition at line 250 of file MappableGridGenerator.cpp.
References GeneratePlane(), and mReferenceLength.
boost::shared_ptr< Part< 3 > > MappableGridGenerator::GeneratePlane (unsigned numX, unsigned numY, bool withEndCaps = true)
Generate a planar grid with one block in the z direction
Parameters
numX number of blocks in the x direction
numY number of blocks in the y direction
withEndCaps include polygons at the ends of the plane, turned off for closed cylinder generation
Returns
pointer to a Part representation of the plane
Definition at line 54 of file MappableGridGenerator.cpp.
References Part< DIM >::Create(), and mReferenceLength.
Referenced by GenerateCylinder(), and GenerateHemisphere().
Member Data Documentation
units::quantity<unit::length> MappableGridGenerator::mReferenceLength private
The reference length scale
Definition at line 51 of file MappableGridGenerator.hpp.
Referenced by GenerateCylinder(), GenerateHemisphere(), and GeneratePlane().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/geometry/generators/MappableGridGenerator.hpp
projects/MicrovesselChaste/src/geometry/generators/MappableGridGenerator.cpp