Chaste: AbstractVesselNetworkComponentProperties< DIM > Class Template Reference
AbstractVesselNetworkComponentProperties< DIM > Class Template Reference abstract
#include <AbstractVesselNetworkComponentProperties.hpp>
Public Member Functions
AbstractVesselNetworkComponentProperties ()
virtual ~AbstractVesselNetworkComponentProperties ()
virtual std::map< std::string, double > GetOutputData () const =0
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AbstractVesselNetworkComponentProperties< DIM >
This class contains common functionality for property containers for all vessel network components. It provides a common interface that can be used in VTK writers.
Definition at line 51 of file AbstractVesselNetworkComponentProperties.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> AbstractVesselNetworkComponentProperties< DIM >::AbstractVesselNetworkComponentProperties ()
Constructor
Definition at line 39 of file AbstractVesselNetworkComponentProperties.cpp.
Referenced by AbstractVesselNetworkComponentProperties< DIM >::serialize().
template<unsigned DIM> AbstractVesselNetworkComponentProperties< DIM >::~AbstractVesselNetworkComponentProperties () virtual
Destructor
Definition at line 45 of file AbstractVesselNetworkComponentProperties.cpp.
Referenced by AbstractVesselNetworkComponentProperties< DIM >::serialize().
Member Function Documentation
template<unsigned DIM> virtual std::map<std::string, double> AbstractVesselNetworkComponentProperties< DIM >::GetOutputData () const pure virtual
Return a map of output data for writing to file
Returns
a map of output data for use by writers
Implemented in SegmentFlowProperties< DIM >, VesselFlowProperties< DIM >, and NodeFlowProperties< DIM >.
Referenced by AbstractVesselNetworkComponentProperties< DIM >::serialize().
template<unsigned DIM> template<class Archive > void AbstractVesselNetworkComponentProperties< DIM >::serialize (Archive & ar, const unsigned int version) inline private
Do the serialize
Parameters
ar the archive
version the archive version number
Definition at line 64 of file AbstractVesselNetworkComponentProperties.hpp.
References AbstractVesselNetworkComponentProperties< DIM >::AbstractVesselNetworkComponentProperties(), AbstractVesselNetworkComponentProperties< DIM >::GetOutputData(), and AbstractVesselNetworkComponentProperties< DIM >::~AbstractVesselNetworkComponentProperties().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Archiving
Definition at line 56 of file AbstractVesselNetworkComponentProperties.hpp.
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/vessel/properties/AbstractVesselNetworkComponentProperties.hpp
projects/MicrovesselChaste/src/population/vessel/properties/AbstractVesselNetworkComponentProperties.cpp