Chaste: RegularGridWriter Class Reference
RegularGridWriter Class Reference
#include <RegularGridWriter.hpp>
Public Member Functions
RegularGridWriter ()
~RegularGridWriter ()
void SetFilename (const std::string &rFilename)
void SetImage (vtkSmartPointer< vtkImageData > pImage)
void Write ()
Static Public Member Functions
static boost::shared_ptr< RegularGridWriter > Create ()
Private Attributes
vtkSmartPointer< vtkImageData > mpVtkImage
std::string mFilepath
Detailed Description
This class that manages output of vtk images (regular structured grids). It is also used for outputting solutions on regular grids.
Definition at line 48 of file RegularGridWriter.hpp.
Constructor & Destructor Documentation
RegularGridWriter::RegularGridWriter ()
Constructor
Definition at line 44 of file RegularGridWriter.cpp.
RegularGridWriter::~RegularGridWriter ()
Destructor
Definition at line 57 of file RegularGridWriter.cpp.
Member Function Documentation
boost::shared_ptr< RegularGridWriter > RegularGridWriter::Create () static
Factory constructor method
Returns
a shared pointer to a instance of this class
Definition at line 51 of file RegularGridWriter.cpp.
void RegularGridWriter::SetFilename (const std::string & rFilename)
Set the filename for the writer
Parameters
rFilename the file name
Definition at line 67 of file RegularGridWriter.cpp.
References mFilepath.
Referenced by AbstractRegularGridDiscreteContinuumSolver< DIM >::Write(), RegularGrid< DIM >::Write(), and GreensFunctionSolver< DIM >::WriteSolution().
void RegularGridWriter::SetImage (vtkSmartPointer< vtkImageData > pImage)
Set the image in vti format
Parameters
pImage
Definition at line 62 of file RegularGridWriter.cpp.
References mpVtkImage.
Referenced by AbstractRegularGridDiscreteContinuumSolver< DIM >::Write(), RegularGrid< DIM >::Write(), and GreensFunctionSolver< DIM >::WriteSolution().
void RegularGridWriter::Write ()
Write the image in VTK format
Definition at line 72 of file RegularGridWriter.cpp.
References mFilepath, and mpVtkImage.
Referenced by AbstractRegularGridDiscreteContinuumSolver< DIM >::Write(), RegularGrid< DIM >::Write(), and GreensFunctionSolver< DIM >::WriteSolution().
Member Data Documentation
std::string RegularGridWriter::mFilepath private
The output path
Definition at line 61 of file RegularGridWriter.hpp.
Referenced by SetFilename(), and Write().
vtkSmartPointer<vtkImageData> RegularGridWriter::mpVtkImage private
The image to be written
Definition at line 56 of file RegularGridWriter.hpp.
Referenced by SetImage(), and Write().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/mesh/RegularGridWriter.hpp
projects/MicrovesselChaste/src/mesh/RegularGridWriter.cpp