Chaste: OffLatticeMigrationRule< DIM > Class Template Reference
OffLatticeMigrationRule< DIM > Class Template Reference
#include <OffLatticeMigrationRule.hpp>
Public Member Functions
OffLatticeMigrationRule ()
virtual ~OffLatticeMigrationRule ()
std::vector< DimensionalChastePoint< DIM > > GetDirections (const std::vector< boost::shared_ptr< VesselNode< DIM > > > &rNodes)
std::vector< DimensionalChastePoint< DIM > > GetDirectionsForSprouts (const std::vector< boost::shared_ptr< VesselNode< DIM > > > &rNodes)
void SetSproutingVelocity (units::quantity< unit::velocity > velocity)
void SetChemotacticStrength (double strength)
void SetAttractionStrength (double strength)
Public Member Functions inherited from AbstractMigrationRule< DIM >
AbstractMigrationRule ()
virtual ~AbstractMigrationRule ()
virtual std::vector< int > GetIndices (const std::vector< boost::shared_ptr< VesselNode< DIM > > > &rNodes)
void SetIsSprouting (bool isSprouting=true)
void SetDiscreteContinuumSolver (boost::shared_ptr< AbstractDiscreteContinuumSolver< DIM > > pSolver)
void SetNetwork (boost::shared_ptr< VesselNetwork< DIM > > pNetwork)
void SetBoundingDomain (boost::shared_ptr< Part< DIM > > pPart)
void SetGrid (boost::shared_ptr< RegularGrid< DIM > > pGrid)
void SetCellPopulation (boost::shared_ptr< AbstractCellPopulation< DIM > > pCellPopulation)
Static Public Member Functions
static boost::shared_ptr< OffLatticeMigrationRule< DIM > > Create ()
Static Public Member Functions inherited from AbstractMigrationRule< DIM >
static boost::shared_ptr< AbstractMigrationRule< DIM > > Create ()
Private Attributes
c_vector< double, 3 > mGlobalX
c_vector< double, 3 > mGlobalY
c_vector< double, 3 > mGlobalZ
std::vector< units::quantity< unit::plane_angle > > mMeanAngles
std::vector< units::quantity< unit::plane_angle > > mSdvAngles
units::quantity< unit::velocity > mVelocity
double mChemotacticStrength
double mAttractionStrength
units::quantity< unit::length > mProbeLength
units::quantity< unit::length > mCriticalMutualAttractionLength
Additional Inherited Members
Protected Attributes inherited from AbstractMigrationRule< DIM >
boost::shared_ptr< AbstractDiscreteContinuumSolver< DIM > > mpSolver
boost::shared_ptr< VesselNetwork< DIM > > mpVesselNetwork
bool mIsSprouting
boost::shared_ptr< AbstractCellPopulation< DIM > > mpCellPopulation
boost::shared_ptr< RegularGrid< DIM > > mpGrid
boost::shared_ptr< Part< DIM > > mpBoundingDomain
Detailed Description
template<unsigned DIM>
class OffLatticeMigrationRule< DIM >
An off-lattice migration rule for tip cells
Definition at line 49 of file OffLatticeMigrationRule.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> OffLatticeMigrationRule< DIM >::OffLatticeMigrationRule ()
Constructor.
Definition at line 42 of file OffLatticeMigrationRule.cpp.
template<unsigned DIM> OffLatticeMigrationRule< DIM >::~OffLatticeMigrationRule () virtual
Destructor.
Definition at line 66 of file OffLatticeMigrationRule.cpp.
Member Function Documentation
template<unsigned DIM> boost::shared_ptr< OffLatticeMigrationRule< DIM > > OffLatticeMigrationRule< DIM >::Create () static
Construct a new instance of the class and return a shared pointer to it.
Returns
pointer to a new class instance
Definition at line 59 of file OffLatticeMigrationRule.cpp.
template<unsigned DIM> std::vector< DimensionalChastePoint< DIM > > OffLatticeMigrationRule< DIM >::GetDirections (const std::vector< boost::shared_ptr< VesselNode< DIM > > > & rNodes) virtual
Return the movement vector (new_location - oriringal_location) for the input nodes, if they can't move set it to the zero vector
Parameters
rNodes nodes to calculate indices
Returns
a vector of movement vectors
Reimplemented from AbstractMigrationRule< DIM >.
Definition at line 90 of file OffLatticeMigrationRule.cpp.
References OffLatticeMigrationRule< DIM >::GetDirectionsForSprouts(), DimensionalChastePoint< DIM >::GetLocation(), DimensionalChastePoint< DIM >::GetReferenceLengthScale(), BaseUnits::GetReferenceTimeScale(), DimensionalChastePoint< DIM >::GetUnitVector(), BaseUnits::Instance(), OffLatticeMigrationRule< DIM >::mAttractionStrength, OffLatticeMigrationRule< DIM >::mChemotacticStrength, OffLatticeMigrationRule< DIM >::mCriticalMutualAttractionLength, OffLatticeMigrationRule< DIM >::mGlobalX, OffLatticeMigrationRule< DIM >::mGlobalY, OffLatticeMigrationRule< DIM >::mGlobalZ, AbstractMigrationRule< DIM >::mIsSprouting, OffLatticeMigrationRule< DIM >::mMeanAngles, AbstractMigrationRule< DIM >::mpBoundingDomain, OffLatticeMigrationRule< DIM >::mProbeLength, AbstractMigrationRule< DIM >::mpSolver, AbstractMigrationRule< DIM >::mpVesselNetwork, OffLatticeMigrationRule< DIM >::mSdvAngles, and OffLatticeMigrationRule< DIM >::mVelocity.
template<unsigned DIM> std::vector< DimensionalChastePoint< DIM > > OffLatticeMigrationRule< DIM >::GetDirectionsForSprouts (const std::vector< boost::shared_ptr< VesselNode< DIM > > > & rNodes)
Get the sprout directions
Parameters
rNodes nodes to calculate directions
Returns
a vector of movement vectors
Definition at line 247 of file OffLatticeMigrationRule.cpp.
References BaseUnits::GetReferenceLengthScale(), BaseUnits::GetReferenceTimeScale(), BaseUnits::Instance(), OffLatticeMigrationRule< DIM >::mMeanAngles, AbstractMigrationRule< DIM >::mpBoundingDomain, OffLatticeMigrationRule< DIM >::mProbeLength, AbstractMigrationRule< DIM >::mpSolver, OffLatticeMigrationRule< DIM >::mSdvAngles, and OffLatticeMigrationRule< DIM >::mVelocity.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections().
template<unsigned DIM> void OffLatticeMigrationRule< DIM >::SetAttractionStrength (double strength)
Set the mutual attraction strength
Parameters
strength the mutual attraction strength
Definition at line 84 of file OffLatticeMigrationRule.cpp.
References OffLatticeMigrationRule< DIM >::mAttractionStrength.
template<unsigned DIM> void OffLatticeMigrationRule< DIM >::SetChemotacticStrength (double strength)
Set the chemotactic strength
Parameters
strength the chemotactic strength
Definition at line 78 of file OffLatticeMigrationRule.cpp.
References OffLatticeMigrationRule< DIM >::mChemotacticStrength.
template<unsigned DIM> void OffLatticeMigrationRule< DIM >::SetSproutingVelocity (units::quantity< unit::velocity > velocity)
Set the sprout velocity
Parameters
velocity the sprout velocity
Definition at line 72 of file OffLatticeMigrationRule.cpp.
References OffLatticeMigrationRule< DIM >::mVelocity.
Member Data Documentation
template<unsigned DIM> double OffLatticeMigrationRule< DIM >::mAttractionStrength private
Vessel-vessel attraction strength
Definition at line 89 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections(), and OffLatticeMigrationRule< DIM >::SetAttractionStrength().
template<unsigned DIM> double OffLatticeMigrationRule< DIM >::mChemotacticStrength private
Chemotactic strength
Definition at line 84 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections(), and OffLatticeMigrationRule< DIM >::SetChemotacticStrength().
template<unsigned DIM> units::quantity<unit::length> OffLatticeMigrationRule< DIM >::mCriticalMutualAttractionLength private
Length beyond which there is no mutual attraction
Definition at line 99 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections().
template<unsigned DIM> c_vector<double, 3> OffLatticeMigrationRule< DIM >::mGlobalX private
Global direction vectors, x (1,0,0)
Definition at line 54 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections().
template<unsigned DIM> c_vector<double, 3> OffLatticeMigrationRule< DIM >::mGlobalY private
Global direction vectors, y (0,1,0)
Definition at line 59 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections().
template<unsigned DIM> c_vector<double, 3> OffLatticeMigrationRule< DIM >::mGlobalZ private
Global direction vectors, z (0,0,1)
Definition at line 64 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections().
template<unsigned DIM> std::vector<units::quantity<unit::plane_angle> > OffLatticeMigrationRule< DIM >::mMeanAngles private
Mean angle between current and new directions about global axes
Definition at line 69 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections(), and OffLatticeMigrationRule< DIM >::GetDirectionsForSprouts().
template<unsigned DIM> units::quantity<unit::length> OffLatticeMigrationRule< DIM >::mProbeLength private
Length of probe into solution
Definition at line 94 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections(), and OffLatticeMigrationRule< DIM >::GetDirectionsForSprouts().
template<unsigned DIM> std::vector<units::quantity<unit::plane_angle> > OffLatticeMigrationRule< DIM >::mSdvAngles private
Deviation in angle between current and new directions about global axes
Definition at line 74 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections(), and OffLatticeMigrationRule< DIM >::GetDirectionsForSprouts().
template<unsigned DIM> units::quantity<unit::velocity> OffLatticeMigrationRule< DIM >::mVelocity private
Tip cell velocity
Definition at line 79 of file OffLatticeMigrationRule.hpp.
Referenced by OffLatticeMigrationRule< DIM >::GetDirections(), OffLatticeMigrationRule< DIM >::GetDirectionsForSprouts(), and OffLatticeMigrationRule< DIM >::SetSproutingVelocity().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/simulation/angiogenesis/migration_rules/off_lattice/OffLatticeMigrationRule.hpp
projects/MicrovesselChaste/src/simulation/angiogenesis/migration_rules/off_lattice/OffLatticeMigrationRule.cpp