Chaste: VesselNetworkCellPopulationInteractor< DIM > Class Template Reference
VesselNetworkCellPopulationInteractor< DIM > Class Template Reference
#include <VesselNetworkCellPopulationInteractor.hpp>
Public Member Functions
VesselNetworkCellPopulationInteractor ()
virtual ~VesselNetworkCellPopulationInteractor ()
void LabelVesselsInCellPopulation (AbstractCellPopulation< DIM > &cellPopulation, units::quantity< unit::length > cellLengthScale, boost::shared_ptr< AbstractCellMutationState > pTipMutationState, boost::shared_ptr< AbstractCellMutationState > pStalkState, double threshold=1.25e-6)
void PartitionNetworkOverCells (AbstractCellPopulation< DIM > &rCellPopulation, units::quantity< unit::length > cellLengthScale, double threshold=1.25e-6)
void KillNonVesselOverlappingCells (AbstractCellPopulation< DIM > &rCellPopulation, units::quantity< unit::length > cellLengthScale, double threshold=1.25e-6)
void KillOverlappingVesselCells (AbstractCellPopulation< DIM > &rCellPopulation, units::quantity< unit::length > cellLengthScale, double threshold=1.25e-6)
void SetVesselNetwork (boost::shared_ptr< VesselNetwork< DIM > > pNetwork)
Protected Attributes
boost::shared_ptr< VesselNetwork< DIM > > mpNetwork
Detailed Description
template<unsigned DIM>
class VesselNetworkCellPopulationInteractor< DIM >
The class manages interactions between vessel networks and cell populations. It helps to 'decompartmentalize' each framework by describe interactions in this class rather than individual population classes.
Definition at line 51 of file VesselNetworkCellPopulationInteractor.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VesselNetworkCellPopulationInteractor< DIM >::VesselNetworkCellPopulationInteractor ()
Constructor.
Definition at line 39 of file VesselNetworkCellPopulationInteractor.cpp.
template<unsigned DIM> VesselNetworkCellPopulationInteractor< DIM >::~VesselNetworkCellPopulationInteractor () virtual
Destructor.
Definition at line 46 of file VesselNetworkCellPopulationInteractor.cpp.
Member Function Documentation
template<unsigned DIM> void VesselNetworkCellPopulationInteractor< DIM >::KillNonVesselOverlappingCells (AbstractCellPopulation< DIM > & rCellPopulation, units::quantity< unit::length > cellLengthScale, double threshold = 1.25e-6)
Remove any cells not overlapping with the vessel network. Does not label the cells.
Parameters
rCellPopulation the cell population
threshold the max distance from a cell location to vessel centre for killing.
Definition at line 106 of file VesselNetworkCellPopulationInteractor.cpp.
References DimensionalChastePoint< DIM >::GetDistance(), and VesselNetworkCellPopulationInteractor< DIM >::mpNetwork.
template<unsigned DIM> void VesselNetworkCellPopulationInteractor< DIM >::KillOverlappingVesselCells (AbstractCellPopulation< DIM > & rCellPopulation, units::quantity< unit::length > cellLengthScale, double threshold = 1.25e-6)
Remove any cells overlapping with the vessel network. Does not label the cells.
Parameters
rCellPopulation the cell population
threshold the max distance from a cell location to vessel centre for killing.
Definition at line 125 of file VesselNetworkCellPopulationInteractor.cpp.
References DimensionalChastePoint< DIM >::GetDistance(), and VesselNetworkCellPopulationInteractor< DIM >::mpNetwork.
template<unsigned DIM> void VesselNetworkCellPopulationInteractor< DIM >::LabelVesselsInCellPopulation (AbstractCellPopulation< DIM > & cellPopulation, units::quantity< unit::length > cellLengthScale, boost::shared_ptr< AbstractCellMutationState > pTipMutationState, boost::shared_ptr< AbstractCellMutationState > pStalkState, double threshold = 1.25e-6)
Set any cells in a population that overlaps with a vessel to either the tip or stalk cell mutation state.
Parameters
cellPopulation the cell population
pTipMutationState the mutation state for vessel tips
pStalkState the mutation state for non tip regions
threshold the max distance from a cell location to vessel centre for labelling
Definition at line 52 of file VesselNetworkCellPopulationInteractor.cpp.
References DimensionalChastePoint< DIM >::GetDistance(), and VesselNetworkCellPopulationInteractor< DIM >::mpNetwork.
template<unsigned DIM> void VesselNetworkCellPopulationInteractor< DIM >::PartitionNetworkOverCells (AbstractCellPopulation< DIM > & rCellPopulation, units::quantity< unit::length > cellLengthScale, double threshold = 1.25e-6)
Divide vessels in the network between cell locations in the cell population by adding new nodes at locations coincident with cells.
Parameters
rCellPopulation the cell population
threshold tolerance for point to vessel calculation
Definition at line 78 of file VesselNetworkCellPopulationInteractor.cpp.
References DimensionalChastePoint< DIM >::GetDistance(), and VesselNetworkCellPopulationInteractor< DIM >::mpNetwork.
Referenced by Owen11CellPopulationGenerator< DIM >::Update().
template<unsigned DIM> void VesselNetworkCellPopulationInteractor< DIM >::SetVesselNetwork (boost::shared_ptr< VesselNetwork< DIM > > pNetwork)
Set the vessel network
Parameters
pNetwork the vessel network
Definition at line 144 of file VesselNetworkCellPopulationInteractor.cpp.
References VesselNetworkCellPopulationInteractor< DIM >::mpNetwork.
Referenced by Owen11CellPopulationGenerator< DIM >::Update().
Member Data Documentation
template<unsigned DIM> boost::shared_ptr<VesselNetwork<DIM> > VesselNetworkCellPopulationInteractor< DIM >::mpNetwork protected
The vessel network can be stored here. The cell population is not stored.
Definition at line 59 of file VesselNetworkCellPopulationInteractor.hpp.
Referenced by VesselNetworkCellPopulationInteractor< DIM >::KillNonVesselOverlappingCells(), VesselNetworkCellPopulationInteractor< DIM >::KillOverlappingVesselCells(), VesselNetworkCellPopulationInteractor< DIM >::LabelVesselsInCellPopulation(), VesselNetworkCellPopulationInteractor< DIM >::PartitionNetworkOverCells(), and VesselNetworkCellPopulationInteractor< DIM >::SetVesselNetwork().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/VesselNetworkCellPopulationInteractor.hpp
projects/MicrovesselChaste/src/population/VesselNetworkCellPopulationInteractor.cpp