Chaste: VesselNetworkWriter< DIM > Class Template Reference
VesselNetworkWriter< DIM > Class Template Reference
#include <VesselNetworkWriter.hpp>
Public Member Functions
VesselNetworkWriter ()
~VesselNetworkWriter ()
void SetVesselNetwork (boost::shared_ptr< VesselNetwork< DIM > > pNetwork)
void SetFileName (const std::string &rFileName)
void Write ()
vtkSmartPointer< vtkPolyData > GetOutput ()
void SetReferenceLengthScale (units::quantity< unit::length > rReferenceLength)
Static Public Member Functions
static boost::shared_ptr< VesselNetworkWriter< DIM > > Create ()
Private Attributes
boost::shared_ptr< VesselNetwork< DIM > > mpVesselNetwork
vtkSmartPointer< vtkPolyData > mpVtkVesselNetwork
bool mIsVtkNetworkUpToDate
std::string mFilename
units::quantity< unit::length > mReferenceLength
Detailed Description
template<unsigned DIM>
class VesselNetworkWriter< DIM >
This class converts a vessel network to a vtk polydata representation, which can be return or written to file.
Definition at line 51 of file VesselNetworkWriter.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VesselNetworkWriter< DIM >::VesselNetworkWriter ()
Constructor
Definition at line 52 of file VesselNetworkWriter.cpp.
template<unsigned DIM> VesselNetworkWriter< DIM >::~VesselNetworkWriter ()
Destructor
Definition at line 63 of file VesselNetworkWriter.cpp.
Member Function Documentation
template<unsigned DIM> boost::shared_ptr< VesselNetworkWriter< DIM > > VesselNetworkWriter< DIM >::Create () static
Construct a new instance of the class and return a shared pointer to it.
Returns
a shared pointer to the class
Definition at line 69 of file VesselNetworkWriter.cpp.
Referenced by MicrovesselSolver< DIM >::Increment(), MicrovesselSolver< DIM >::Run(), AngiogenesisSolver< DIM >::Run(), and VesselNetwork< DIM >::Write().
template<unsigned DIM> vtkSmartPointer< vtkPolyData > VesselNetworkWriter< DIM >::GetOutput ()
Return a vtk representation of the network
Returns
the network in vtk form
Definition at line 89 of file VesselNetworkWriter.cpp.
References AbstractVesselNetworkComponent< DIM >::GetId(), Vessel< DIM >::GetNode(), VesselNetworkWriter< DIM >::mIsVtkNetworkUpToDate, VesselNetworkWriter< DIM >::mpVesselNetwork, VesselNetworkWriter< DIM >::mpVtkVesselNetwork, and VesselNetworkWriter< DIM >::mReferenceLength.
Referenced by VesselNetworkActorGenerator< DIM >::AddActor(), and VesselNetworkWriter< DIM >::Write().
template<unsigned DIM> void VesselNetworkWriter< DIM >::SetFileName (const std::string & rFileName)
Adds a collection of vessels to the VesselNetwork
Parameters
rFileName the full output path
Definition at line 213 of file VesselNetworkWriter.cpp.
References VesselNetworkWriter< DIM >::mFilename.
template<unsigned DIM> void VesselNetworkWriter< DIM >::SetReferenceLengthScale (units::quantity< unit::length > rReferenceLength)
Set the reference length scale
Parameters
rReferenceLength the reference length scale
Definition at line 83 of file VesselNetworkWriter.cpp.
References VesselNetworkWriter< DIM >::mReferenceLength.
template<unsigned DIM> void VesselNetworkWriter< DIM >::SetVesselNetwork (boost::shared_ptr< VesselNetwork< DIM > > pNetwork)
Set the vessel network
Parameters
pNetwork the vessel network
Definition at line 76 of file VesselNetworkWriter.cpp.
References VesselNetworkWriter< DIM >::mIsVtkNetworkUpToDate, and VesselNetworkWriter< DIM >::mpVesselNetwork.
Referenced by VesselNetworkActorGenerator< DIM >::AddActor().
template<unsigned DIM> void VesselNetworkWriter< DIM >::Write ()
Do the write
Definition at line 219 of file VesselNetworkWriter.cpp.
References VesselNetworkWriter< DIM >::GetOutput(), and VesselNetworkWriter< DIM >::mFilename.
Member Data Documentation
template<unsigned DIM> std::string VesselNetworkWriter< DIM >::mFilename private
The output file name
Definition at line 74 of file VesselNetworkWriter.hpp.
Referenced by VesselNetworkWriter< DIM >::SetFileName(), and VesselNetworkWriter< DIM >::Write().
template<unsigned DIM> bool VesselNetworkWriter< DIM >::mIsVtkNetworkUpToDate private
Is the current vtk representation up to date
Definition at line 69 of file VesselNetworkWriter.hpp.
Referenced by VesselNetworkWriter< DIM >::GetOutput(), and VesselNetworkWriter< DIM >::SetVesselNetwork().
template<unsigned DIM> boost::shared_ptr<VesselNetwork<DIM> > VesselNetworkWriter< DIM >::mpVesselNetwork private
Container for the vessel network
Definition at line 59 of file VesselNetworkWriter.hpp.
Referenced by VesselNetworkWriter< DIM >::GetOutput(), and VesselNetworkWriter< DIM >::SetVesselNetwork().
template<unsigned DIM> vtkSmartPointer<vtkPolyData> VesselNetworkWriter< DIM >::mpVtkVesselNetwork private
A vtk representation of the network
Definition at line 64 of file VesselNetworkWriter.hpp.
Referenced by VesselNetworkWriter< DIM >::GetOutput().
template<unsigned DIM> units::quantity<unit::length> VesselNetworkWriter< DIM >::mReferenceLength private
The reference length scale for the output.
Definition at line 79 of file VesselNetworkWriter.hpp.
Referenced by VesselNetworkWriter< DIM >::GetOutput(), and VesselNetworkWriter< DIM >::SetReferenceLengthScale().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/vessel/writers/VesselNetworkWriter.hpp
projects/MicrovesselChaste/src/population/vessel/writers/VesselNetworkWriter.cpp