Chaste: DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM > Class Template Reference
DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <DiscreteContinuumMeshGenerator.hpp>
Public Member Functions
DiscreteContinuumMeshGenerator ()
~DiscreteContinuumMeshGenerator ()
boost::shared_ptr< DiscreteContinuumMesh< ELEMENT_DIM, SPACE_DIM > > GetMesh ()
void SetDomain (boost::shared_ptr< Part< SPACE_DIM > > pDomain)
void SetDomain (vtkSmartPointer< vtkPolyData > pDomain)
void SetDomain (const std::string &rPathToStl)
void SetMaxElementArea (units::quantity< unit::volume > maxElementArea)
void SetHoles (std::vector< DimensionalChastePoint< SPACE_DIM > > holes)
void SetRegionMarkers (std::vector< DimensionalChastePoint< SPACE_DIM > > regionMarkers)
void Update ()
Static Public Member Functions
static boost::shared_ptr< DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM > > Create ()
Private Member Functions
void Mesh2d ()
void Mesh3d ()
void MeshStl3d ()
void InitialiseTriangulateIo (triangulateio &mesherIo)
void FreeTriangulateIo (triangulateio &mesherIo)
Private Attributes
units::quantity< unit::volume > mMaxElementArea
boost::shared_ptr< DiscreteContinuumMesh< ELEMENT_DIM, SPACE_DIM > > mpMesh
boost::shared_ptr< Part< SPACE_DIM > > mpDomain
vtkSmartPointer< vtkPolyData > mpVtkDomain
std::string mStlFilePath
std::vector< DimensionalChastePoint< SPACE_DIM > > mHoles
std::vector< DimensionalChastePoint< SPACE_DIM > > mRegions
std::vector< unsigned > mAttributes
units::quantity< unit::length > mReferenceLength
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >
This class is for generating 2d and 3d finite element meshes using triangle and tetgen.
Definition at line 59 of file DiscreteContinuumMesh.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::DiscreteContinuumMeshGenerator ()
Constructor
Definition at line 55 of file DiscreteContinuumMeshGenerator.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::~DiscreteContinuumMeshGenerator ()
Destructor
Definition at line 77 of file DiscreteContinuumMeshGenerator.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> boost::shared_ptr< DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM > > DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Create () static
Factory constructor method
Returns
a shared pointer to a new mesh generator
Definition at line 70 of file DiscreteContinuumMeshGenerator.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::FreeTriangulateIo (triangulateio & mesherIo) private
This is the same as the TetrahedralMesh implementation of InitialiseTriangulateIo but avoids some templating
Parameters
mesherIo the mesher input
Definition at line 516 of file DiscreteContinuumMeshGenerator.cpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> boost::shared_ptr< DiscreteContinuumMesh< ELEMENT_DIM, SPACE_DIM > > DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::GetMesh ()
Return the mesh
Returns
the mesh
Definition at line 83 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpMesh.
Referenced by ImageToMesh< DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::InitialiseTriangulateIo (triangulateio & mesherIo) private
This is the same as the TetrahedralMesh implementation of InitialiseTriangulateIo but avoids some templating
Parameters
mesherIo the mesher input
Definition at line 496 of file DiscreteContinuumMeshGenerator.cpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d () private
Use triangle for 2-D meshing
Definition at line 192 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::FreeTriangulateIo(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::InitialiseTriangulateIo(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mAttributes, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mHoles, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mMaxElementArea, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpDomain, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpMesh, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpVtkDomain, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mReferenceLength, and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mRegions.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh3d () private
Use tetgen for 3-D meshing
Definition at line 365 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mHoles, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mMaxElementArea, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpDomain, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpMesh, and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mReferenceLength.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::MeshStl3d () private
Use tetgen for 3-D meshing of an stl
Definition at line 456 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mHoles, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mMaxElementArea, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpMesh, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mReferenceLength, and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mStlFilePath.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetDomain (boost::shared_ptr< Part< SPACE_DIM > > pDomain)
Set the domain for meshing
Parameters
pDomain the domain for meshing
Definition at line 93 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpDomain.
Referenced by ImageToMesh< DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetDomain (vtkSmartPointer< vtkPolyData > pDomain)
Set the domain for meshing
Parameters
pDomain the domain for meshing
Definition at line 99 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpVtkDomain.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetDomain (const std::string & rPathToStl)
Set the domain for meshing
Parameters
rPathToStl the path to the stl for meshing
Definition at line 105 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mStlFilePath.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetHoles (std::vector< DimensionalChastePoint< SPACE_DIM > > holes)
Set the hole locations
Parameters
holes hole locations
Definition at line 117 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mHoles.
Referenced by ImageToMesh< DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetMaxElementArea (units::quantity< unit::volume > maxElementArea)
Set the max element area
Parameters
maxElementArea the max element area
Definition at line 111 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mMaxElementArea.
Referenced by ImageToMesh< DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetRegionMarkers (std::vector< DimensionalChastePoint< SPACE_DIM > > regionMarkers)
Set the region marker locations
Parameters
regionMarkers region marker locations
Definition at line 123 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mRegions.
Referenced by ImageToMesh< DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Update ()
Do the meshing
Definition at line 129 of file DiscreteContinuumMeshGenerator.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh3d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::MeshStl3d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpDomain, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpMesh, and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpVtkDomain.
Referenced by ImageToMesh< DIM >::Update().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> std::vector<unsigned> DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mAttributes private
Store element-wise region markers
Definition at line 108 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> std::vector<DimensionalChastePoint<SPACE_DIM> > DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mHoles private
A collection of hole location markers
Definition at line 98 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh3d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::MeshStl3d(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetHoles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> units::quantity<unit::volume> DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mMaxElementArea private
Max area argument used in mesh generation.
Definition at line 73 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh3d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::MeshStl3d(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetMaxElementArea().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> boost::shared_ptr<Part<SPACE_DIM> > DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpDomain private
A part to be meshed. This may not be the final mesh geometry if extra vtk polydata is included.
Definition at line 83 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh3d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetDomain(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> boost::shared_ptr<DiscreteContinuumMesh<ELEMENT_DIM, SPACE_DIM> > DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpMesh private
The mesh
Definition at line 78 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::GetMesh(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh3d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::MeshStl3d(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> vtkSmartPointer<vtkPolyData> DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mpVtkDomain private
A vtk surface to be meshed
Definition at line 88 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetDomain(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Update().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> units::quantity<unit::length> DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mReferenceLength private
The reference length scale for the mesh
Definition at line 113 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh3d(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::MeshStl3d().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> std::vector<DimensionalChastePoint<SPACE_DIM> > DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mRegions private
A collection of region markers
Definition at line 103 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Mesh2d(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetRegionMarkers().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> std::string DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::mStlFilePath private
A path to an stl surface to be meshed
Definition at line 93 of file DiscreteContinuumMeshGenerator.hpp.
Referenced by DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::MeshStl3d(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetDomain().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/mesh/DiscreteContinuumMesh.hpp
projects/MicrovesselChaste/src/mesh/DiscreteContinuumMeshGenerator.hpp
projects/MicrovesselChaste/src/mesh/DiscreteContinuumMeshGenerator.cpp