Chaste: Owen11CaUpdateRule< DIM > Class Template Reference
Owen11CaUpdateRule< DIM > Class Template Reference
#include <Owen11CaUpdateRule.hpp>
Public Member Functions
Owen11CaUpdateRule ()
~Owen11CaUpdateRule ()
double EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, CaBasedCellPopulation< DIM > &rCellPopulation, double dt, double deltaX, CellPtr cell)
units::quantity< unit::diffusivity > GetDiffusionParameter ()
void SetVesselNetwork (boost::shared_ptr< VesselNetwork< DIM > > pVesselNetwork)
void SetRegularGrid (boost::shared_ptr< RegularGrid< DIM > > pRegularGrid)
void SetReferenceLengthScale (units::quantity< unit::length > referenceLengthScale)
void SetDiffusionParameter (units::quantity< unit::diffusivity > diffusionParameter)
void OutputUpdateRuleParameters (out_stream &rParamsFile)
template<>
double EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, CaBasedCellPopulation< 1 > &rCellPopulation, double dt, double deltaX, CellPtr pCell)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
units::quantity< unit::diffusivity > mDiffusionParameter
boost::shared_ptr< VesselNetwork< DIM > > mpVesselNetwork
boost::shared_ptr< RegularGrid< DIM > > mpRegularGrid
units::quantity< unit::length > mReferenceLengthScale
unsigned mCancerCellCarryingCapacity
Friends
class TestCaUpdateRules
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class Owen11CaUpdateRule< DIM >
A diffusion update rule based loosely on Owen et al. 2001. Vessels are treated differently to the paper, as they have their own sprouting and migration rules. However they can occupy space.
The probability of moving to an adjacent lattice site is
D*delta_t*((Nm-N)Nm)/(2*delta_xy)
Where D is the mDiffusionParameter. delta_t is the timestep. delta_xy is the separation of the two lattice sites. Nm is the carrying capacity for the cell type N is the number of cells at the lattice site
In this manifestation only cancer cells diffuse.
Definition at line 65 of file Owen11CaUpdateRule.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> Owen11CaUpdateRule< DIM >::Owen11CaUpdateRule ()
Constructor.
Definition at line 43 of file Owen11CaUpdateRule.cpp.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
template<unsigned DIM> Owen11CaUpdateRule< DIM >::~Owen11CaUpdateRule ()
Destructor.
Definition at line 55 of file Owen11CaUpdateRule.cpp.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
Member Function Documentation
template<> double Owen11CaUpdateRule< 1 >::EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, CaBasedCellPopulation< 1 > & rCellPopulation, double dt, double deltaX, CellPtr pCell)
Specialization to allow used with 1D classes
Parameters
currentNodeIndex the current index
targetNodeIndex the target index
rCellPopulation the cell population
dt the time increment
deltaX the grid spacing
pCell the cell
Returns
the movement probability
Definition at line 113 of file Owen11CaUpdateRule.cpp.
template<unsigned DIM> double Owen11CaUpdateRule< DIM >::EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, CaBasedCellPopulation< DIM > & rCellPopulation, double dt, double deltaX, CellPtr cell)
Calculate the probability of a given move.
Uses random diffusion to each neighbouring node, scaled according to distance.
Parameters
currentNodeIndex The index of the current node/lattice site
targetNodeIndex The index of the target node/lattice site
rCellPopulation The cell population
dt is the time interval
deltaX defines the size of the lattice site
cell a pointer to the cell (needed if more than one cell per lattice site
Returns
The probability of the cell moving from the current node to the target node
Definition at line 60 of file Owen11CaUpdateRule.cpp.
References BaseUnits::GetReferenceTimeScale(), BaseUnits::Instance(), Owen11CaUpdateRule< DIM >::mCancerCellCarryingCapacity, Owen11CaUpdateRule< DIM >::mDiffusionParameter, Owen11CaUpdateRule< DIM >::mpRegularGrid, Owen11CaUpdateRule< DIM >::mpVesselNetwork, and Owen11CaUpdateRule< DIM >::mReferenceLengthScale.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
template<unsigned DIM> units::quantity< unit::diffusivity > Owen11CaUpdateRule< DIM >::GetDiffusionParameter ()
Returns
mDiffusionParameter
Definition at line 142 of file Owen11CaUpdateRule.cpp.
References Owen11CaUpdateRule< DIM >::mDiffusionParameter.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
template<unsigned DIM> void Owen11CaUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile)
Overridden OutputUpdateRuleParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Definition at line 154 of file Owen11CaUpdateRule.cpp.
References Owen11CaUpdateRule< DIM >::mDiffusionParameter.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
template<unsigned DIM> template<class Archive > void Owen11CaUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 105 of file Owen11CaUpdateRule.hpp.
References Owen11CaUpdateRule< DIM >::EvaluateProbability(), Owen11CaUpdateRule< DIM >::GetDiffusionParameter(), Owen11CaUpdateRule< DIM >::mCancerCellCarryingCapacity, Owen11CaUpdateRule< DIM >::mDiffusionParameter, Owen11CaUpdateRule< DIM >::mReferenceLengthScale, Owen11CaUpdateRule< DIM >::OutputUpdateRuleParameters(), Owen11CaUpdateRule< DIM >::Owen11CaUpdateRule(), Owen11CaUpdateRule< DIM >::SetDiffusionParameter(), Owen11CaUpdateRule< DIM >::SetReferenceLengthScale(), Owen11CaUpdateRule< DIM >::SetRegularGrid(), Owen11CaUpdateRule< DIM >::SetVesselNetwork(), and Owen11CaUpdateRule< DIM >::~Owen11CaUpdateRule().
template<unsigned DIM> void Owen11CaUpdateRule< DIM >::SetDiffusionParameter (units::quantity< unit::diffusivity > diffusionParameter)
Set mDiffusionParameter.
Parameters
diffusionParameter the new value of mDiffusionParameter
Definition at line 148 of file Owen11CaUpdateRule.cpp.
References Owen11CaUpdateRule< DIM >::mDiffusionParameter.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
template<unsigned DIM> void Owen11CaUpdateRule< DIM >::SetReferenceLengthScale (units::quantity< unit::length > referenceLengthScale)
Set the reference length scale
Parameters
referenceLengthScale the reference length scale
Definition at line 130 of file Owen11CaUpdateRule.cpp.
References Owen11CaUpdateRule< DIM >::mReferenceLengthScale.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
template<unsigned DIM> void Owen11CaUpdateRule< DIM >::SetRegularGrid (boost::shared_ptr< RegularGrid< DIM > > pRegularGrid)
Set the regular grid
Parameters
pRegularGrid The regular grid
Definition at line 136 of file Owen11CaUpdateRule.cpp.
References Owen11CaUpdateRule< DIM >::mpRegularGrid.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
template<unsigned DIM> void Owen11CaUpdateRule< DIM >::SetVesselNetwork (boost::shared_ptr< VesselNetwork< DIM > > pVesselNetwork)
Set the vessel network
Parameters
pVesselNetwork The vessel network
Definition at line 124 of file Owen11CaUpdateRule.cpp.
References Owen11CaUpdateRule< DIM >::mpVesselNetwork.
Referenced by Owen11CaUpdateRule< DIM >::serialize().
Member Data Documentation
template<unsigned DIM> unsigned Owen11CaUpdateRule< DIM >::mCancerCellCarryingCapacity private
Cancer cell carrying capacity
Definition at line 94 of file Owen11CaUpdateRule.hpp.
Referenced by Owen11CaUpdateRule< DIM >::EvaluateProbability(), and Owen11CaUpdateRule< DIM >::serialize().
template<unsigned DIM> units::quantity<unit::diffusivity> Owen11CaUpdateRule< DIM >::mDiffusionParameter private
Diffusion parameter for update rule.
Definition at line 74 of file Owen11CaUpdateRule.hpp.
Referenced by Owen11CaUpdateRule< DIM >::EvaluateProbability(), Owen11CaUpdateRule< DIM >::GetDiffusionParameter(), Owen11CaUpdateRule< DIM >::OutputUpdateRuleParameters(), Owen11CaUpdateRule< DIM >::serialize(), and Owen11CaUpdateRule< DIM >::SetDiffusionParameter().
template<unsigned DIM> boost::shared_ptr<RegularGrid<DIM> > Owen11CaUpdateRule< DIM >::mpRegularGrid private
Regular Grid
Definition at line 84 of file Owen11CaUpdateRule.hpp.
Referenced by Owen11CaUpdateRule< DIM >::EvaluateProbability(), and Owen11CaUpdateRule< DIM >::SetRegularGrid().
template<unsigned DIM> boost::shared_ptr<VesselNetwork<DIM> > Owen11CaUpdateRule< DIM >::mpVesselNetwork private
Vessel network
Definition at line 79 of file Owen11CaUpdateRule.hpp.
Referenced by Owen11CaUpdateRule< DIM >::EvaluateProbability(), and Owen11CaUpdateRule< DIM >::SetVesselNetwork().
template<unsigned DIM> units::quantity<unit::length> Owen11CaUpdateRule< DIM >::mReferenceLengthScale private
Reference length scale
Definition at line 89 of file Owen11CaUpdateRule.hpp.
Referenced by Owen11CaUpdateRule< DIM >::EvaluateProbability(), Owen11CaUpdateRule< DIM >::serialize(), and Owen11CaUpdateRule< DIM >::SetReferenceLengthScale().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/cell/Owen11CaUpdateRule.hpp
projects/MicrovesselChaste/src/population/cell/Owen11CaUpdateRule.cpp