Chaste: VoronoiGenerator< DIM > Class Template Reference
VoronoiGenerator< DIM > Class Template Reference
#include <VoronoiGenerator.hpp>
Public Member Functions
VoronoiGenerator ()
~VoronoiGenerator ()
boost::shared_ptr< Part< DIM > > Generate (boost::shared_ptr< Part< DIM > > pPart, std::vector< boost::shared_ptr< DimensionalChastePoint< DIM > > > seeds=std::vector< boost::shared_ptr< DimensionalChastePoint< DIM > > >(), unsigned numSeeds=100)
Private Attributes
units::quantity< unit::length > mReferenceLength
Detailed Description
template<unsigned DIM>
class VoronoiGenerator< DIM >
Generate a voronoi tesselation in the bounding box of a given part. If point seeds are not given generate them randomly.
Definition at line 50 of file VoronoiGenerator.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VoronoiGenerator< DIM >::VoronoiGenerator ()
Constructor
Definition at line 59 of file VoronoiGenerator.cpp.
template<unsigned DIM> VoronoiGenerator< DIM >::~VoronoiGenerator ()
Destructor
Definition at line 65 of file VoronoiGenerator.cpp.
Member Function Documentation
template<unsigned DIM> boost::shared_ptr< Part< DIM > > VoronoiGenerator< DIM >::Generate (boost::shared_ptr< Part< DIM > > pPart, std::vector< boost::shared_ptr< DimensionalChastePoint< DIM > > > seeds = std::vector<boost::shared_ptr<DimensionalChastePoint<DIM> > >(), unsigned numSeeds = 100)
Generate a voronoi tesselation in the bounding box of the part
Parameters
pPart the part to generate in
seeds an optional collection of initial point seeds
numSeeds the number of seed points, if initial seeds are not given.
Returns
a new part corresponding to the voronoi tessellation
Definition at line 71 of file VoronoiGenerator.cpp.
References Polygon< DIM >::Create(), Part< DIM >::Create(), DimensionalChastePoint< DIM >::Create(), and VoronoiGenerator< DIM >::mReferenceLength.
Referenced by VesselNetworkGenerator< DIM >::SetReferenceLengthScale().
Member Data Documentation
template<unsigned DIM> units::quantity<unit::length> VoronoiGenerator< DIM >::mReferenceLength private
The reference length scale
Definition at line 55 of file VoronoiGenerator.hpp.
Referenced by VoronoiGenerator< DIM >::Generate().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/geometry/generators/VoronoiGenerator.hpp
projects/MicrovesselChaste/src/geometry/generators/VoronoiGenerator.cpp