Chaste: SegmentFlowProperties< DIM > Class Template Reference
SegmentFlowProperties< DIM > Class Template Reference
#include <SegmentFlowProperties.hpp>
Public Member Functions
SegmentFlowProperties ()
~SegmentFlowProperties ()
units::quantity< unit::dimensionless > GetHaematocrit () const
units::quantity< unit::flow_impedance > GetImpedance () const
units::quantity< unit::flow_rate > GetFlowRate () const
units::quantity< unit::dynamic_viscosity > GetViscosity () const
units::quantity< unit::pressure > GetWallShearStress () const
units::quantity< unit::rate > GetGrowthStimulus () const
std::map< std::string, double > GetOutputData () const
void SetHaematocrit (units::quantity< unit::dimensionless > haematocrit)
void SetFlowRate (units::quantity< unit::flow_rate > flowRate)
void SetImpedance (units::quantity< unit::flow_impedance > impedance)
void SetViscosity (units::quantity< unit::dynamic_viscosity > viscosity)
void SetWallShearStress (units::quantity< unit::pressure > wallShear)
void SetGrowthStimulus (units::quantity< unit::rate > stimulus)
Public Member Functions inherited from AbstractVesselNetworkComponentFlowProperties< DIM >
AbstractVesselNetworkComponentFlowProperties ()
virtual ~AbstractVesselNetworkComponentFlowProperties ()
units::quantity< unit::pressure > GetPressure () const
virtual void SetPressure (units::quantity< unit::pressure > pressure)
Public Member Functions inherited from AbstractVesselNetworkComponentProperties< DIM >
AbstractVesselNetworkComponentProperties ()
virtual ~AbstractVesselNetworkComponentProperties ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
units::quantity< unit::dimensionless > mHaematocrit
units::quantity< unit::flow_rate > mFlowRate
units::quantity< unit::flow_impedance > mImpedance
units::quantity< unit::dynamic_viscosity > mViscosity
units::quantity< unit::pressure > mWallShearStress
units::quantity< unit::rate > mStimulus
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractVesselNetworkComponentFlowProperties< DIM >
units::quantity< unit::pressure > mPressure
Detailed Description
template<unsigned DIM>
class SegmentFlowProperties< DIM >
This is a class for vessel segment flow properties.
This class stores segment data for vessel network flow problems. Each segment has an instance of the class.
Definition at line 53 of file SegmentFlowProperties.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> SegmentFlowProperties< DIM >::SegmentFlowProperties ()
Constructor
Definition at line 39 of file SegmentFlowProperties.cpp.
template<unsigned DIM> SegmentFlowProperties< DIM >::~SegmentFlowProperties ()
Destructor
Definition at line 50 of file SegmentFlowProperties.cpp.
Member Function Documentation
template<unsigned DIM> units::quantity< unit::flow_rate > SegmentFlowProperties< DIM >::GetFlowRate () const
Return the flow rate
Returns
the segment flow rate
Definition at line 61 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mFlowRate.
Referenced by SegmentFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> units::quantity< unit::rate > SegmentFlowProperties< DIM >::GetGrowthStimulus () const
Return the growth stimulus of this vessel segment
Returns
the segment growth stimulus
Definition at line 85 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mStimulus.
Referenced by SegmentFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> units::quantity< unit::dimensionless > SegmentFlowProperties< DIM >::GetHaematocrit () const
Return the haematocrit
Returns
the segment haematocrit
Definition at line 55 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mHaematocrit.
Referenced by SegmentFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> units::quantity< unit::flow_impedance > SegmentFlowProperties< DIM >::GetImpedance () const
Return the impedance
Returns
the segment impedance
Definition at line 67 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mImpedance.
Referenced by SegmentFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> std::map< std::string, double > SegmentFlowProperties< DIM >::GetOutputData () const virtual
Return a map of segment data for use by the vtk writer
Returns
a map of segment data for use by the vtk writer
Implements AbstractVesselNetworkComponentProperties< DIM >.
Definition at line 91 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::GetFlowRate(), SegmentFlowProperties< DIM >::GetGrowthStimulus(), SegmentFlowProperties< DIM >::GetHaematocrit(), SegmentFlowProperties< DIM >::GetImpedance(), SegmentFlowProperties< DIM >::GetViscosity(), and SegmentFlowProperties< DIM >::GetWallShearStress().
template<unsigned DIM> units::quantity< unit::dynamic_viscosity > SegmentFlowProperties< DIM >::GetViscosity () const
Return the segment viscosity
Returns
the segment viscosity
Definition at line 73 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mViscosity.
Referenced by SegmentFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> units::quantity< unit::pressure > SegmentFlowProperties< DIM >::GetWallShearStress () const
Return the segment wall shear stress
Returns
the segment wall shear stress
Definition at line 79 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mWallShearStress.
Referenced by SegmentFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> template<class Archive > void SegmentFlowProperties< DIM >::serialize (Archive & ar, const unsigned int version) inline private
Do the serialize
Parameters
ar the archive
version the archive version number
Definition at line 69 of file SegmentFlowProperties.hpp.
References SegmentFlowProperties< DIM >::mFlowRate, SegmentFlowProperties< DIM >::mHaematocrit, SegmentFlowProperties< DIM >::mImpedance, SegmentFlowProperties< DIM >::mStimulus, SegmentFlowProperties< DIM >::mViscosity, and SegmentFlowProperties< DIM >::mWallShearStress.
template<unsigned DIM> void SegmentFlowProperties< DIM >::SetFlowRate (units::quantity< unit::flow_rate > flowRate)
Set the flow rate
Parameters
flowRate the flow rate in the segment
Definition at line 110 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mFlowRate.
template<unsigned DIM> void SegmentFlowProperties< DIM >::SetGrowthStimulus (units::quantity< unit::rate > stimulus)
Set the growth stimulus of this vessel segment
Parameters
stimulus the growth stimulus in the segment
Definition at line 134 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mStimulus.
template<unsigned DIM> void SegmentFlowProperties< DIM >::SetHaematocrit (units::quantity< unit::dimensionless > haematocrit)
Set the haematocrit
Parameters
haematocrit the haematocrit in the segment
Definition at line 104 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mHaematocrit.
template<unsigned DIM> void SegmentFlowProperties< DIM >::SetImpedance (units::quantity< unit::flow_impedance > impedance)
Set the impedance
Parameters
impedance the impedance in the segment
Definition at line 116 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mImpedance.
template<unsigned DIM> void SegmentFlowProperties< DIM >::SetViscosity (units::quantity< unit::dynamic_viscosity > viscosity)
Set the viscosity
Parameters
viscosity the viscosity in the segment
Definition at line 122 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mViscosity.
template<unsigned DIM> void SegmentFlowProperties< DIM >::SetWallShearStress (units::quantity< unit::pressure > wallShear)
Set the wall shear stress of this vessel segment
Parameters
wallShear the wall shear stress in the segment
Definition at line 128 of file SegmentFlowProperties.cpp.
References SegmentFlowProperties< DIM >::mWallShearStress.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Archiving
Definition at line 61 of file SegmentFlowProperties.hpp.
Member Data Documentation
template<unsigned DIM> units::quantity<unit::flow_rate> SegmentFlowProperties< DIM >::mFlowRate private
Blood flow rate in the vessel at this segment
Definition at line 88 of file SegmentFlowProperties.hpp.
Referenced by SegmentFlowProperties< DIM >::GetFlowRate(), SegmentFlowProperties< DIM >::serialize(), and SegmentFlowProperties< DIM >::SetFlowRate().
template<unsigned DIM> units::quantity<unit::dimensionless> SegmentFlowProperties< DIM >::mHaematocrit private
Haematocrit in the vessel at this segment
Definition at line 83 of file SegmentFlowProperties.hpp.
Referenced by SegmentFlowProperties< DIM >::GetHaematocrit(), SegmentFlowProperties< DIM >::serialize(), and SegmentFlowProperties< DIM >::SetHaematocrit().
template<unsigned DIM> units::quantity<unit::flow_impedance> SegmentFlowProperties< DIM >::mImpedance private
Impedance of this vessel segment
Definition at line 93 of file SegmentFlowProperties.hpp.
Referenced by SegmentFlowProperties< DIM >::GetImpedance(), SegmentFlowProperties< DIM >::serialize(), and SegmentFlowProperties< DIM >::SetImpedance().
template<unsigned DIM> units::quantity<unit::rate> SegmentFlowProperties< DIM >::mStimulus private
Growth stimulus of this vessel segment
Definition at line 108 of file SegmentFlowProperties.hpp.
Referenced by SegmentFlowProperties< DIM >::GetGrowthStimulus(), SegmentFlowProperties< DIM >::serialize(), and SegmentFlowProperties< DIM >::SetGrowthStimulus().
template<unsigned DIM> units::quantity<unit::dynamic_viscosity> SegmentFlowProperties< DIM >::mViscosity private
Viscosity of this vessel segment
Definition at line 98 of file SegmentFlowProperties.hpp.
Referenced by SegmentFlowProperties< DIM >::GetViscosity(), SegmentFlowProperties< DIM >::serialize(), and SegmentFlowProperties< DIM >::SetViscosity().
template<unsigned DIM> units::quantity<unit::pressure> SegmentFlowProperties< DIM >::mWallShearStress private
Wall shear stress of this vessel segment
Definition at line 103 of file SegmentFlowProperties.hpp.
Referenced by SegmentFlowProperties< DIM >::GetWallShearStress(), SegmentFlowProperties< DIM >::serialize(), and SegmentFlowProperties< DIM >::SetWallShearStress().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/vessel/properties/SegmentFlowProperties.hpp
projects/MicrovesselChaste/src/population/vessel/properties/SegmentFlowProperties.cpp