Chaste: Owen2011TrackingModifier< DIM > Class Template Reference
Owen2011TrackingModifier< DIM > Class Template Reference
#include <Owen2011TrackingModifier.hpp>
Public Member Functions
Owen2011TrackingModifier ()
virtual ~Owen2011TrackingModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< DIM, DIM > &rCellPopulation, std::string outputDirectory)
void UpdateCellData (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
void OutputSimulationModifierParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class Owen2011TrackingModifier< DIM >
A modifier class to store in Cell Properties in CellData.
Definition at line 48 of file Owen2011TrackingModifier.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> Owen2011TrackingModifier< DIM >::Owen2011TrackingModifier ()
Default constructor.
Definition at line 44 of file Owen2011TrackingModifier.cpp.
Referenced by Owen2011TrackingModifier< DIM >::serialize().
template<unsigned DIM> Owen2011TrackingModifier< DIM >::~Owen2011TrackingModifier () virtual
Destructor.
Definition at line 50 of file Owen2011TrackingModifier.cpp.
Referenced by Owen2011TrackingModifier< DIM >::serialize().
Member Function Documentation
template<unsigned DIM> void Owen2011TrackingModifier< DIM >::OutputSimulationModifierParameters (out_stream & rParamsFile)
Overridden OutputSimulationModifierParameters() method. Output any simulation modifier parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Definition at line 127 of file Owen2011TrackingModifier.cpp.
Referenced by Owen2011TrackingModifier< DIM >::serialize().
template<unsigned DIM> template<class Archive > void Owen2011TrackingModifier< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 60 of file Owen2011TrackingModifier.hpp.
References Owen2011TrackingModifier< DIM >::OutputSimulationModifierParameters(), Owen2011TrackingModifier< DIM >::Owen2011TrackingModifier(), Owen2011TrackingModifier< DIM >::SetupSolve(), Owen2011TrackingModifier< DIM >::UpdateAtEndOfTimeStep(), Owen2011TrackingModifier< DIM >::UpdateCellData(), and Owen2011TrackingModifier< DIM >::~Owen2011TrackingModifier().
template<unsigned DIM> void Owen2011TrackingModifier< DIM >::SetupSolve (AbstractCellPopulation< DIM, DIM > & rCellPopulation, std::string outputDirectory) virtual
Overridden SetupSolve() method.
Specifies what to do in the simulation before the start of the time loop.
Parameters
rCellPopulation reference to the cell population
outputDirectory the output directory, relative to where Chaste output is stored
Definition at line 61 of file Owen2011TrackingModifier.cpp.
References Owen2011TrackingModifier< DIM >::UpdateCellData().
Referenced by Owen2011TrackingModifier< DIM >::serialize().
template<unsigned DIM> void Owen2011TrackingModifier< DIM >::UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > & rCellPopulation) virtual
Overridden UpdateAtEndOfTimeStep() method.
Specifies what to do in the simulation at the end of each time step.
Parameters
rCellPopulation reference to the cell population
Definition at line 55 of file Owen2011TrackingModifier.cpp.
References Owen2011TrackingModifier< DIM >::UpdateCellData().
Referenced by Owen2011TrackingModifier< DIM >::serialize().
template<unsigned DIM> void Owen2011TrackingModifier< DIM >::UpdateCellData (AbstractCellPopulation< DIM, DIM > & rCellPopulation)
Helper method to store cell properties in the CellData.
Parameters
rCellPopulation reference to the cell population
Definition at line 71 of file Owen2011TrackingModifier.cpp.
References Owen2011OxygenBasedCellCycleModel::GetP53(), Owen2011OxygenBasedCellCycleModel::GetPhi(), and Owen2011OxygenBasedCellCycleModel::GetVEGF().
Referenced by Owen2011TrackingModifier< DIM >::serialize(), Owen2011TrackingModifier< DIM >::SetupSolve(), and Owen2011TrackingModifier< DIM >::UpdateAtEndOfTimeStep().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 51 of file Owen2011TrackingModifier.hpp.
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/ode/Owen2011TrackingModifier.hpp
projects/MicrovesselChaste/src/ode/Owen2011TrackingModifier.cpp