Chaste: LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM > Class Template Reference
LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <LinearSteadyStateDiffusionReactionPde.hpp>
Public Member Functions
LinearSteadyStateDiffusionReactionPde ()
~LinearSteadyStateDiffusionReactionPde ()
double ComputeLinearInUCoeffInSourceTerm (const ChastePoint< SPACE_DIM > &rX, Element< ELEMENT_DIM, SPACE_DIM > *pElement)
units::quantity< unit::rate > ComputeLinearInUCoeffInSourceTerm (unsigned gridIndex=0)
void SetContinuumLinearInUTerm (units::quantity< unit::rate > linearInUTerm)
void UpdateDiscreteSourceStrengths ()
Public Member Functions inherited from AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >
AbstractDiscreteContinuumLinearEllipticPde ()
virtual ~AbstractDiscreteContinuumLinearEllipticPde ()
void AddDiscreteSource (boost::shared_ptr< DiscreteSource< SPACE_DIM > > pDiscreteSource)
double ComputeConstantInUSourceTerm (const ChastePoint< SPACE_DIM > &rX, Element< ELEMENT_DIM, SPACE_DIM > *pElement)
units::quantity< unit::concentration_flow_rate > ComputeConstantInUSourceTerm (unsigned gridIndex=0)
c_matrix< double, SPACE_DIM, SPACE_DIM > ComputeDiffusionTerm (const ChastePoint< SPACE_DIM > &)
units::quantity< unit::diffusivity > ComputeIsotropicDiffusionTerm ()
std::vector< boost::shared_ptr< DiscreteSource< SPACE_DIM > > > GetDiscreteSources ()
void SetContinuumConstantInUTerm (units::quantity< unit::concentration_flow_rate > constantInUTerm)
void SetIsotropicDiffusionConstant (units::quantity< unit::diffusivity > diffusivity)
void SetRegularGrid (boost::shared_ptr< RegularGrid< SPACE_DIM > > pRegularGrid)
void SetMesh (boost::shared_ptr< DiscreteContinuumMesh< ELEMENT_DIM, SPACE_DIM > > pMesh)
void SetReferenceConcentration (units::quantity< unit::concentration > referenceConcentration)
void SetUseRegularGrid (bool useRegularGrid)
Static Public Member Functions
static boost::shared_ptr< LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM > > Create ()
Private Attributes
units::quantity< unit::rate > mLinearInUTerm
std::vector< units::quantity< unit::rate > > mDiscreteLinearSourceStrengths
Additional Inherited Members
Protected Attributes inherited from AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >
c_matrix< double, SPACE_DIM, SPACE_DIM > mDiffusionTensor
units::quantity< unit::diffusivity > mDiffusivity
units::quantity< unit::concentration_flow_rate > mConstantInUTerm
std::vector< boost::shared_ptr< DiscreteSource< SPACE_DIM > > > mDiscreteSources
boost::shared_ptr< RegularGrid< SPACE_DIM > > mpRegularGrid
boost::shared_ptr< DiscreteContinuumMesh< ELEMENT_DIM, SPACE_DIM > > mpMesh
bool mUseRegularGrid
std::vector< units::quantity< unit::concentration_flow_rate > > mDiscreteConstantSourceStrengths
units::quantity< unit::concentration > mReferenceConcentration
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >
Linear reaction diffusion PDE
Definition at line 49 of file LinearSteadyStateDiffusionReactionPde.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::LinearSteadyStateDiffusionReactionPde ()
Constructor
Definition at line 41 of file LinearSteadyStateDiffusionReactionPde.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::~LinearSteadyStateDiffusionReactionPde ()
Destructor
Definition at line 50 of file LinearSteadyStateDiffusionReactionPde.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::ComputeLinearInUCoeffInSourceTerm (const ChastePoint< SPACE_DIM > & rX, Element< ELEMENT_DIM, SPACE_DIM > * pElement)
Overwritten method to return the linear in U contribution to the Chaste FE solver
Parameters
rX grid location
pElement pointer to containing element
Returns
source strength
Definition at line 63 of file LinearSteadyStateDiffusionReactionPde.cpp.
References BaseUnits::GetReferenceTimeScale(), BaseUnits::Instance(), LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::mDiscreteLinearSourceStrengths, and LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::mLinearInUTerm.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> units::quantity< unit::rate > LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::ComputeLinearInUCoeffInSourceTerm (unsigned gridIndex = 0) virtual
Overwritten method to return the linear in U contribution to the regular grid solvers
Parameters
gridIndex grid index
Returns
source strength
Implements AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >.
Definition at line 83 of file LinearSteadyStateDiffusionReactionPde.cpp.
References LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::mDiscreteLinearSourceStrengths, and LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::mLinearInUTerm.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> boost::shared_ptr< LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM > > LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::Create () static
Factory Constructor
Returns
a pointer to an instance of the pde
Definition at line 56 of file LinearSteadyStateDiffusionReactionPde.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::SetContinuumLinearInUTerm (units::quantity< unit::rate > linearInUTerm)
Set the linear constant in U term
Parameters
linearInUTerm the linear constant in U term
Definition at line 100 of file LinearSteadyStateDiffusionReactionPde.cpp.
References LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::mLinearInUTerm.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::UpdateDiscreteSourceStrengths () virtual
Update the discrete source strengths
Reimplemented from AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >.
Definition at line 106 of file LinearSteadyStateDiffusionReactionPde.cpp.
References LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::mDiscreteLinearSourceStrengths, AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::mDiscreteSources, AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::mpMesh, AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::mpRegularGrid, AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::mUseRegularGrid, and AbstractDiscreteContinuumLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::UpdateDiscreteSourceStrengths().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> std::vector<units::quantity<unit::rate> > LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::mDiscreteLinearSourceStrengths private
The linear source strengths for each point on the grid or mesh
Definition at line 59 of file LinearSteadyStateDiffusionReactionPde.hpp.
Referenced by LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::ComputeLinearInUCoeffInSourceTerm(), and LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::UpdateDiscreteSourceStrengths().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> units::quantity<unit::rate> LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::mLinearInUTerm private
The continuum linear in U term, discrete terms are added to this.
Definition at line 54 of file LinearSteadyStateDiffusionReactionPde.hpp.
Referenced by LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::ComputeLinearInUCoeffInSourceTerm(), and LinearSteadyStateDiffusionReactionPde< ELEMENT_DIM, SPACE_DIM >::SetContinuumLinearInUTerm().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/pde/problem/LinearSteadyStateDiffusionReactionPde.hpp
projects/MicrovesselChaste/src/pde/problem/LinearSteadyStateDiffusionReactionPde.cpp