Chaste: NodeFlowProperties< DIM > Class Template Reference
NodeFlowProperties< DIM > Class Template Reference
#include <NodeFlowProperties.hpp>
Public Member Functions
NodeFlowProperties ()
~NodeFlowProperties ()
std::map< std::string, double > GetOutputData () const
bool IsInputNode () const
bool IsOutputNode () const
void SetIsInputNode (bool isInput)
void SetIsOutputNode (bool isOutput)
void SetUseVelocityBoundaryCondition (bool useVelocity)
bool UseVelocityBoundaryCondition ()
Public Member Functions inherited from AbstractVesselNetworkComponentFlowProperties< DIM >
AbstractVesselNetworkComponentFlowProperties ()
virtual ~AbstractVesselNetworkComponentFlowProperties ()
units::quantity< unit::pressure > GetPressure () const
virtual void SetPressure (units::quantity< unit::pressure > pressure)
Public Member Functions inherited from AbstractVesselNetworkComponentProperties< DIM >
AbstractVesselNetworkComponentProperties ()
virtual ~AbstractVesselNetworkComponentProperties ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
bool mIsInputNode
bool mIsOutputNode
bool mUseVelocityBoundaryCondition
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractVesselNetworkComponentFlowProperties< DIM >
units::quantity< unit::pressure > mPressure
Detailed Description
template<unsigned DIM>
class NodeFlowProperties< DIM >
This is a class for vascular node flow properties.
This class stores nodal data for vessel network flow problems. Each node has an instance of the class.
Definition at line 52 of file NodeFlowProperties.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> NodeFlowProperties< DIM >::NodeFlowProperties ()
Constructor
Definition at line 39 of file NodeFlowProperties.cpp.
template<unsigned DIM> NodeFlowProperties< DIM >::~NodeFlowProperties ()
Destructor
Definition at line 48 of file NodeFlowProperties.cpp.
Member Function Documentation
template<unsigned DIM> std::map< std::string, double > NodeFlowProperties< DIM >::GetOutputData () const virtual
Return a map of nodal data for use by the vtk writer
Returns
a map of nodal data for use by the vtk writer
Implements AbstractVesselNetworkComponentProperties< DIM >.
Definition at line 54 of file NodeFlowProperties.cpp.
References AbstractVesselNetworkComponentFlowProperties< DIM >::GetPressure(), NodeFlowProperties< DIM >::IsInputNode(), and NodeFlowProperties< DIM >::IsOutputNode().
template<unsigned DIM> bool NodeFlowProperties< DIM >::IsInputNode () const
Return true if the node is an input node
Returns
true if the node is an input node
Definition at line 64 of file NodeFlowProperties.cpp.
References NodeFlowProperties< DIM >::mIsInputNode.
Referenced by NodeFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> bool NodeFlowProperties< DIM >::IsOutputNode () const
Return true if the node is an output node
Returns
true if the node is an output node
Definition at line 70 of file NodeFlowProperties.cpp.
References NodeFlowProperties< DIM >::mIsOutputNode.
Referenced by NodeFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> template<class Archive > void NodeFlowProperties< DIM >::serialize (Archive & ar, const unsigned int version) inline private
Do the serialize
Parameters
ar the archive
version the archive version number
Definition at line 68 of file NodeFlowProperties.hpp.
References NodeFlowProperties< DIM >::mIsInputNode, NodeFlowProperties< DIM >::mIsOutputNode, and NodeFlowProperties< DIM >::mUseVelocityBoundaryCondition.
template<unsigned DIM> void NodeFlowProperties< DIM >::SetIsInputNode (bool isInput)
Set that the node is an input node
Parameters
isInput whether the node is an input
Definition at line 76 of file NodeFlowProperties.cpp.
References NodeFlowProperties< DIM >::mIsInputNode.
template<unsigned DIM> void NodeFlowProperties< DIM >::SetIsOutputNode (bool isOutput)
Set that the node is an output node
Parameters
isOutput whether the node is an output
Definition at line 82 of file NodeFlowProperties.cpp.
References NodeFlowProperties< DIM >::mIsOutputNode.
template<unsigned DIM> void NodeFlowProperties< DIM >::SetUseVelocityBoundaryCondition (bool useVelocity)
Set whether to use inlet velocity boundary conditions for flow calculations
Parameters
useVelocity whether to use inlet velocity boundary conditions for flow calculations
Definition at line 88 of file NodeFlowProperties.cpp.
References NodeFlowProperties< DIM >::mUseVelocityBoundaryCondition.
template<unsigned DIM> bool NodeFlowProperties< DIM >::UseVelocityBoundaryCondition ()
Whether to use inlet velocity boundary conditions for flow calculations
Returns
whether inlet velocity conditions are used
Definition at line 94 of file NodeFlowProperties.cpp.
References NodeFlowProperties< DIM >::mUseVelocityBoundaryCondition.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Archiving
Definition at line 60 of file NodeFlowProperties.hpp.
Member Data Documentation
template<unsigned DIM> bool NodeFlowProperties< DIM >::mIsInputNode private
Is the node an input node
Definition at line 79 of file NodeFlowProperties.hpp.
Referenced by NodeFlowProperties< DIM >::IsInputNode(), NodeFlowProperties< DIM >::serialize(), and NodeFlowProperties< DIM >::SetIsInputNode().
template<unsigned DIM> bool NodeFlowProperties< DIM >::mIsOutputNode private
Is the node an output node
Definition at line 84 of file NodeFlowProperties.hpp.
Referenced by NodeFlowProperties< DIM >::IsOutputNode(), NodeFlowProperties< DIM >::serialize(), and NodeFlowProperties< DIM >::SetIsOutputNode().
template<unsigned DIM> bool NodeFlowProperties< DIM >::mUseVelocityBoundaryCondition private
Whether to use the nodal pressure or segment velocity as a boundary condition
Definition at line 89 of file NodeFlowProperties.hpp.
Referenced by NodeFlowProperties< DIM >::serialize(), NodeFlowProperties< DIM >::SetUseVelocityBoundaryCondition(), and NodeFlowProperties< DIM >::UseVelocityBoundaryCondition().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/vessel/properties/NodeFlowProperties.hpp
projects/MicrovesselChaste/src/population/vessel/properties/NodeFlowProperties.cpp