Chaste: BoundaryExtractor Class Reference
BoundaryExtractor Class Reference
#include <BoundaryExtractor.hpp>
Public Member Functions
BoundaryExtractor ()
~BoundaryExtractor ()
vtkSmartPointer< vtkPolyData > GetOutput ()
void SetInput (vtkSmartPointer< vtkPolyData > pInputSurface)
void SetSmoothingLength (double value)
void SetDoSmoothing (bool doSmoothing)
void Update ()
Static Public Member Functions
static boost::shared_ptr< BoundaryExtractor > Create ()
Private Attributes
vtkSmartPointer< vtkPolyData > mpInputSurface
vtkSmartPointer< vtkPolyData > mpOutputSurface
double mSmoothingLength
bool mDoSmoothing
Detailed Description
This class extracts exterior boundaries from 2D surfaces defined as vtk polydata. It includes methods for smoothing the resulting line boundary using spline resampling of the boundary.
Definition at line 48 of file BoundaryExtractor.hpp.
Constructor & Destructor Documentation
BoundaryExtractor::BoundaryExtractor ()
Constructor
Definition at line 45 of file BoundaryExtractor.cpp.
BoundaryExtractor::~BoundaryExtractor ()
Destructor
Definition at line 60 of file BoundaryExtractor.cpp.
Member Function Documentation
boost::shared_ptr< BoundaryExtractor > BoundaryExtractor::Create () static
Factory constructor method
Returns
a pointer to a class instance
Definition at line 54 of file BoundaryExtractor.cpp.
vtkSmartPointer< vtkPolyData > BoundaryExtractor::GetOutput ()
Get the boundary edges
Returns
the boundary edges
Definition at line 65 of file BoundaryExtractor.cpp.
References mpOutputSurface.
Referenced by ImageToMesh< DIM >::Update().
void BoundaryExtractor::SetDoSmoothing (bool doSmoothing)
Whether to do the smoothing
Parameters
doSmoothing whether to do the smoothing
Definition at line 87 of file BoundaryExtractor.cpp.
References mDoSmoothing.
Referenced by ImageToMesh< DIM >::Update().
void BoundaryExtractor::SetInput (vtkSmartPointer< vtkPolyData > pInputSurface)
A 2D surface from which boundary edges are to be extracted
Parameters
pInputSurface the surface
Definition at line 77 of file BoundaryExtractor.cpp.
References mpInputSurface.
Referenced by ImageToMesh< DIM >::Update().
void BoundaryExtractor::SetSmoothingLength (double value)
A length for the spline resampling filter
Parameters
value the resampling length
Definition at line 82 of file BoundaryExtractor.cpp.
References mSmoothingLength.
Referenced by ImageToMesh< DIM >::Update().
void BoundaryExtractor::Update ()
Run the tool
Definition at line 92 of file BoundaryExtractor.cpp.
References mDoSmoothing, mpInputSurface, mpOutputSurface, and mSmoothingLength.
Referenced by ImageToMesh< DIM >::Update().
Member Data Documentation
bool BoundaryExtractor::mDoSmoothing private
Whether or not to do smoothing
Definition at line 68 of file BoundaryExtractor.hpp.
Referenced by SetDoSmoothing(), and Update().
vtkSmartPointer<vtkPolyData> BoundaryExtractor::mpInputSurface private
The input surface
Definition at line 53 of file BoundaryExtractor.hpp.
Referenced by SetInput(), and Update().
vtkSmartPointer<vtkPolyData> BoundaryExtractor::mpOutputSurface private
The output surface
Definition at line 58 of file BoundaryExtractor.hpp.
Referenced by GetOutput(), and Update().
double BoundaryExtractor::mSmoothingLength private
A characteristic length for the spline resampling, a greater length leads to more smoothing.
Definition at line 63 of file BoundaryExtractor.hpp.
Referenced by SetSmoothingLength(), and Update().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/geometry/tools/BoundaryExtractor.hpp
projects/MicrovesselChaste/src/geometry/tools/BoundaryExtractor.cpp