Chaste: ImageToMesh< DIM > Class Template Reference
ImageToMesh< DIM > Class Template Reference
#include <ImageToMesh.hpp>
Public Member Functions
ImageToMesh ()
~ImageToMesh ()
boost::shared_ptr< DiscreteContinuumMesh< DIM, DIM > > GetMesh ()
void SetElementSize (units::quantity< unit::volume > elementSize)
void SetInput (vtkSmartPointer< vtkImageData > pImage)
void SetInputRaw (vtkImageData *pImage)
void SetTissueDomain (boost::shared_ptr< Part< DIM > > pTissueDomain)
void Update ()
Static Public Member Functions
static boost::shared_ptr< ImageToMesh< DIM > > Create ()
Private Attributes
vtkSmartPointer< vtkImageData > mpImage
units::quantity< unit::volume > mElementSize
boost::shared_ptr< DiscreteContinuumMesh< DIM, DIM > > mMesh
boost::shared_ptr< Part< DIM > > mpDomain
Detailed Description
template<unsigned DIM>
class ImageToMesh< DIM >
Do finite element meshing of a region in an image
Definition at line 50 of file ImageToMesh.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> ImageToMesh< DIM >::ImageToMesh ()
Constructor
Definition at line 54 of file ImageToMesh.cpp.
template<unsigned DIM> ImageToMesh< DIM >::~ImageToMesh ()
Destructor
Definition at line 71 of file ImageToMesh.cpp.
Member Function Documentation
template<unsigned DIM> boost::shared_ptr< ImageToMesh< DIM > > ImageToMesh< DIM >::Create () static
Factory constructor method
Definition at line 64 of file ImageToMesh.cpp.
template<unsigned DIM> boost::shared_ptr< DiscreteContinuumMesh< DIM, DIM > > ImageToMesh< DIM >::GetMesh ()
Get the mesh
Definition at line 77 of file ImageToMesh.cpp.
References ImageToMesh< DIM >::mMesh.
template<unsigned DIM> void ImageToMesh< DIM >::SetElementSize (units::quantity< unit::volume > elementSize)
Set the element size
Definition at line 96 of file ImageToMesh.cpp.
References ImageToMesh< DIM >::mElementSize.
template<unsigned DIM> void ImageToMesh< DIM >::SetInput (vtkSmartPointer< vtkImageData > pImage)
Set the image to be meshed
Definition at line 102 of file ImageToMesh.cpp.
References ImageToMesh< DIM >::mpImage.
template<unsigned DIM> void ImageToMesh< DIM >::SetInputRaw (vtkImageData * pImage)
Set the image to be meshed using a raw pointer, needed for Python wrapping
Definition at line 108 of file ImageToMesh.cpp.
References ImageToMesh< DIM >::mpImage.
template<unsigned DIM> void ImageToMesh< DIM >::SetTissueDomain (boost::shared_ptr< Part< DIM > > pTissueDomain)
Add a tissue domain to the mesh
Parameters
pTissueDomain a tissue domain for meshing
Definition at line 90 of file ImageToMesh.cpp.
References ImageToMesh< DIM >::mpDomain.
template<unsigned DIM> void ImageToMesh< DIM >::Update ()
Do the meshing
Definition at line 115 of file ImageToMesh.cpp.
References DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::GetMesh(), BoundaryExtractor::GetOutput(), ImageToMesh< DIM >::mElementSize, ImageToMesh< DIM >::mMesh, ImageToMesh< DIM >::mpDomain, ImageToMesh< DIM >::mpImage, DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetDomain(), BoundaryExtractor::SetDoSmoothing(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetHoles(), BoundaryExtractor::SetInput(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetMaxElementArea(), DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::SetRegionMarkers(), BoundaryExtractor::SetSmoothingLength(), BoundaryExtractor::Update(), and DiscreteContinuumMeshGenerator< ELEMENT_DIM, SPACE_DIM >::Update().
Member Data Documentation
template<unsigned DIM> units::quantity<unit::volume> ImageToMesh< DIM >::mElementSize private
The target element size
Definition at line 60 of file ImageToMesh.hpp.
Referenced by ImageToMesh< DIM >::SetElementSize(), and ImageToMesh< DIM >::Update().
template<unsigned DIM> boost::shared_ptr<DiscreteContinuumMesh<DIM, DIM> > ImageToMesh< DIM >::mMesh private
The mesh
Definition at line 65 of file ImageToMesh.hpp.
Referenced by ImageToMesh< DIM >::GetMesh(), and ImageToMesh< DIM >::Update().
template<unsigned DIM> boost::shared_ptr<Part<DIM> > ImageToMesh< DIM >::mpDomain private
Tissue domain (optional)
Definition at line 70 of file ImageToMesh.hpp.
Referenced by ImageToMesh< DIM >::SetTissueDomain(), and ImageToMesh< DIM >::Update().
template<unsigned DIM> vtkSmartPointer<vtkImageData> ImageToMesh< DIM >::mpImage private
The image
Definition at line 55 of file ImageToMesh.hpp.
Referenced by ImageToMesh< DIM >::SetInput(), ImageToMesh< DIM >::SetInputRaw(), and ImageToMesh< DIM >::Update().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/image/ImageToMesh.hpp
projects/MicrovesselChaste/src/image/ImageToMesh.cpp