Chaste: AbstractVesselNetworkComponent< DIM > Class Template Reference
AbstractVesselNetworkComponent< DIM > Class Template Reference abstract
#include <AbstractVesselNetworkComponent.hpp>
Public Member Functions
AbstractVesselNetworkComponent ()
virtual ~AbstractVesselNetworkComponent ()
virtual unsigned GetId () const
virtual double GetOutputDataValue (const std::string &rKey)
virtual std::map< std::string, double > GetOutputData ()=0
virtual std::vector< std::string > GetOutputDataKeys ()
virtual units::quantity< unit::length > GetRadius () const
virtual void SetId (unsigned id)
virtual void SetOutputData (const std::string &rKey, double value)
virtual void SetRadius (units::quantity< unit::length > radius)
Protected Attributes
std::map< std::string, double > mOutputData
unsigned mId
units::quantity< unit::length > mRadius
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AbstractVesselNetworkComponent< DIM >
This class contains functionality common to all components of a vessel network.
Definition at line 54 of file AbstractVesselNetworkComponent.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> AbstractVesselNetworkComponent< DIM >::AbstractVesselNetworkComponent ()
Constructor.
Definition at line 40 of file AbstractVesselNetworkComponent.cpp.
template<unsigned DIM> AbstractVesselNetworkComponent< DIM >::~AbstractVesselNetworkComponent () virtual
Destructor
Definition at line 49 of file AbstractVesselNetworkComponent.cpp.
Member Function Documentation
template<unsigned DIM> unsigned AbstractVesselNetworkComponent< DIM >::GetId () const virtual
Return the component Id
Returns
the component id
Definition at line 54 of file AbstractVesselNetworkComponent.cpp.
References AbstractVesselNetworkComponent< DIM >::mId.
Referenced by VesselNetworkWriter< DIM >::GetOutput(), VesselSegment< DIM >::GetOutputData(), VesselNode< DIM >::GetOutputData(), and Vessel< DIM >::GetOutputData().
template<unsigned DIM> virtual std::map<std::string, double> AbstractVesselNetworkComponent< DIM >::GetOutputData () pure virtual
Return a map of output data for writers
Returns
a map of component data for use by the vtk writer
Implemented in VesselNetwork< DIM >, Vessel< DIM >, VesselNode< DIM >, and VesselSegment< DIM >.
Referenced by AbstractVesselNetworkComponent< DIM >::GetOutputDataKeys(), and AbstractVesselNetworkComponent< DIM >::GetOutputDataValue().
template<unsigned DIM> std::vector< std::string > AbstractVesselNetworkComponent< DIM >::GetOutputDataKeys () virtual
Return the keys of the output data map
Returns
a map of component data for use by the vtk writer
Definition at line 77 of file AbstractVesselNetworkComponent.cpp.
References AbstractVesselNetworkComponent< DIM >::GetOutputData(), and AbstractVesselNetworkComponent< DIM >::mOutputData.
template<unsigned DIM> double AbstractVesselNetworkComponent< DIM >::GetOutputDataValue (const std::string & rKey) virtual
Return the output data for the given key. This method is relatively slow compared to GetOutputData as the data map is reconstructed each time. It is used by the Python framework.
Parameters
rKey the key to be queried
Returns
the component data for the input key
Definition at line 60 of file AbstractVesselNetworkComponent.cpp.
References AbstractVesselNetworkComponent< DIM >::GetOutputData(), and AbstractVesselNetworkComponent< DIM >::mOutputData.
template<unsigned DIM> units::quantity< unit::length > AbstractVesselNetworkComponent< DIM >::GetRadius () const virtual
Return the radius of the component
Returns
the radius of the component
Reimplemented in Vessel< DIM >.
Definition at line 91 of file AbstractVesselNetworkComponent.cpp.
References AbstractVesselNetworkComponent< DIM >::mRadius.
Referenced by VesselSegment< DIM >::GetOutputData(), and VesselNode< DIM >::GetOutputData().
template<unsigned DIM> template<class Archive > void AbstractVesselNetworkComponent< DIM >::serialize (Archive & ar, const unsigned int version) inline private
Do the serialize
Parameters
ar the archive
version the archive version number
Definition at line 67 of file AbstractVesselNetworkComponent.hpp.
template<unsigned DIM> void AbstractVesselNetworkComponent< DIM >::SetId (unsigned id) virtual
Assign the Id
Parameters
id the id for the component
Definition at line 103 of file AbstractVesselNetworkComponent.cpp.
References AbstractVesselNetworkComponent< DIM >::mId.
template<unsigned DIM> void AbstractVesselNetworkComponent< DIM >::SetOutputData (const std::string & rKey, double value) virtual
Add output data to the component using the identifying key
Parameters
rKey the key for the data being assigned to the node
value the value to be stored
Definition at line 97 of file AbstractVesselNetworkComponent.cpp.
References AbstractVesselNetworkComponent< DIM >::mOutputData.
template<unsigned DIM> void AbstractVesselNetworkComponent< DIM >::SetRadius (units::quantity< unit::length > radius) virtual
Set the component radius
Parameters
radius the component radius
Reimplemented in Vessel< DIM >.
Definition at line 109 of file AbstractVesselNetworkComponent.cpp.
References AbstractVesselNetworkComponent< DIM >::mRadius.
Referenced by VesselSegment< DIM >::CopyDataFromExistingSegment().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Archiving
Definition at line 59 of file AbstractVesselNetworkComponent.hpp.
Member Data Documentation
template<unsigned DIM> unsigned AbstractVesselNetworkComponent< DIM >::mId protected
Id tag, useful for post-processing
Definition at line 82 of file AbstractVesselNetworkComponent.hpp.
Referenced by AbstractVesselNetworkComponent< DIM >::GetId(), and AbstractVesselNetworkComponent< DIM >::SetId().
template<unsigned DIM> std::map<std::string, double> AbstractVesselNetworkComponent< DIM >::mOutputData protected
Container for generic component data.
Definition at line 77 of file AbstractVesselNetworkComponent.hpp.
Referenced by VesselSegment< DIM >::CopyDataFromExistingSegment(), Vessel< DIM >::CopyDataFromExistingVessel(), VesselSegment< DIM >::GetOutputData(), VesselNode< DIM >::GetOutputData(), Vessel< DIM >::GetOutputData(), VesselNetwork< DIM >::GetOutputData(), AbstractVesselNetworkComponent< DIM >::GetOutputDataKeys(), AbstractVesselNetworkComponent< DIM >::GetOutputDataValue(), and AbstractVesselNetworkComponent< DIM >::SetOutputData().
template<unsigned DIM> units::quantity<unit::length> AbstractVesselNetworkComponent< DIM >::mRadius protected
The component radius
Definition at line 87 of file AbstractVesselNetworkComponent.hpp.
Referenced by AbstractVesselNetworkComponent< DIM >::GetRadius(), and AbstractVesselNetworkComponent< DIM >::SetRadius().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/vessel/AbstractVesselNetworkComponent.hpp
projects/MicrovesselChaste/src/population/vessel/AbstractVesselNetworkComponent.cpp