Chaste: VesselFlowProperties< DIM > Class Template Reference
VesselFlowProperties< DIM > Class Template Reference
#include <VesselFlowProperties.hpp>
Public Member Functions
VesselFlowProperties ()
~VesselFlowProperties ()
void CheckSegments () const
units::quantity< unit::dimensionless > GetHaematocrit () const
units::quantity< unit::flow_impedance > GetImpedance () const
units::quantity< unit::flow_rate > GetFlowRate () const
units::quantity< unit::dynamic_viscosity > GetViscosity () const
units::quantity< unit::pressure > GetWallShearStress () const
units::quantity< unit::rate > GetGrowthStimulus () const
std::map< std::string, double > GetOutputData () const
units::quantity< unit::time > GetRegressionTime () const
bool HasRegressionTimerStarted ()
bool HasVesselRegressed (units::quantity< unit::time > simulationReferenceTime)
void ResetRegressionTimer ()
void SetHaematocrit (units::quantity< unit::dimensionless > haematocrit)
void SetFlowRate (units::quantity< unit::flow_rate > flowRate)
void SetImpedance (units::quantity< unit::flow_impedance > impedance)
void SetViscosity (units::quantity< unit::dynamic_viscosity > viscosity)
void SetWallShearStress (units::quantity< unit::pressure > wallShear)
void SetGrowthStimulus (units::quantity< unit::rate > stimulus)
void SetTimeUntilRegression (units::quantity< unit::time > time, units::quantity< unit::time > simulationReferenceTime)
void SetRegressionTime (units::quantity< unit::time > time)
void UpdateSegments (std::vector< boost::shared_ptr< VesselSegment< DIM > > > segments)
Public Member Functions inherited from AbstractVesselNetworkComponentFlowProperties< DIM >
AbstractVesselNetworkComponentFlowProperties ()
virtual ~AbstractVesselNetworkComponentFlowProperties ()
units::quantity< unit::pressure > GetPressure () const
virtual void SetPressure (units::quantity< unit::pressure > pressure)
Public Member Functions inherited from AbstractVesselNetworkComponentProperties< DIM >
AbstractVesselNetworkComponentProperties ()
virtual ~AbstractVesselNetworkComponentProperties ()
Private Attributes
std::vector< boost::shared_ptr< VesselSegment< DIM > > > mSegments
bool mUndergoingRegression
bool mRemoveViaRegression
units::quantity< unit::time > mRegressionTime
Additional Inherited Members
Protected Attributes inherited from AbstractVesselNetworkComponentFlowProperties< DIM >
units::quantity< unit::pressure > mPressure
Detailed Description
template<unsigned DIM>
class VesselFlowProperties< DIM >
This is a class for vessel flow properties.
This class calculates vessel data for vessel network flow problems. Each vessel has an instance of the class.
Definition at line 57 of file VesselFlowProperties.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VesselFlowProperties< DIM >::VesselFlowProperties ()
Constructor
Definition at line 39 of file VesselFlowProperties.cpp.
template<unsigned DIM> VesselFlowProperties< DIM >::~VesselFlowProperties ()
Destructor
Definition at line 48 of file VesselFlowProperties.cpp.
Member Function Documentation
template<unsigned DIM> void VesselFlowProperties< DIM >::CheckSegments () const
Throw an exception if no segments have been set.
Definition at line 53 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::mSegments.
Referenced by VesselFlowProperties< DIM >::GetFlowRate(), VesselFlowProperties< DIM >::GetGrowthStimulus(), VesselFlowProperties< DIM >::GetHaematocrit(), VesselFlowProperties< DIM >::GetImpedance(), VesselFlowProperties< DIM >::GetViscosity(), VesselFlowProperties< DIM >::GetWallShearStress(), VesselFlowProperties< DIM >::SetFlowRate(), VesselFlowProperties< DIM >::SetGrowthStimulus(), VesselFlowProperties< DIM >::SetHaematocrit(), VesselFlowProperties< DIM >::SetImpedance(), VesselFlowProperties< DIM >::SetViscosity(), and VesselFlowProperties< DIM >::SetWallShearStress().
template<unsigned DIM> units::quantity< unit::flow_rate > VesselFlowProperties< DIM >::GetFlowRate () const
Return the flow rate
Returns
the segment flow rate
Definition at line 75 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
Referenced by VesselFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> units::quantity< unit::rate > VesselFlowProperties< DIM >::GetGrowthStimulus () const
Return the growth stimulus of this vessel segment
Returns
the segment growth stimulus
Definition at line 127 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
Referenced by VesselFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> units::quantity< unit::dimensionless > VesselFlowProperties< DIM >::GetHaematocrit () const
Return the 'dimensional' haematocrit
Returns
the segment haematocrit
Definition at line 62 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
Referenced by VesselFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> units::quantity< unit::flow_impedance > VesselFlowProperties< DIM >::GetImpedance () const
Return the impedance
Returns
the segment impedance
Definition at line 88 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
Referenced by VesselFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> std::map< std::string, double > VesselFlowProperties< DIM >::GetOutputData () const virtual
Return a map of segment data for use by the vtk writer
Returns
a map of segment data for use by the vtk writer
Implements AbstractVesselNetworkComponentProperties< DIM >.
Definition at line 140 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::GetFlowRate(), VesselFlowProperties< DIM >::GetGrowthStimulus(), VesselFlowProperties< DIM >::GetHaematocrit(), VesselFlowProperties< DIM >::GetImpedance(), VesselFlowProperties< DIM >::GetViscosity(), VesselFlowProperties< DIM >::GetWallShearStress(), and VesselFlowProperties< DIM >::mRegressionTime.
template<unsigned DIM> units::quantity< unit::time > VesselFlowProperties< DIM >::GetRegressionTime () const
Return the regression time
Returns
the regression time
Definition at line 155 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::mRegressionTime.
template<unsigned DIM> units::quantity< unit::dynamic_viscosity > VesselFlowProperties< DIM >::GetViscosity () const
Return the segment viscosity
Returns
the segment viscosity
Definition at line 101 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
Referenced by VesselFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> units::quantity< unit::pressure > VesselFlowProperties< DIM >::GetWallShearStress () const
Return the segment wall shear stress of this vessel segment
Returns
the segment wall shear stress
Definition at line 114 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
Referenced by VesselFlowProperties< DIM >::GetOutputData().
template<unsigned DIM> bool VesselFlowProperties< DIM >::HasRegressionTimerStarted ()
Returns
whether regression timer has started.
Definition at line 268 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::mUndergoingRegression.
Referenced by VesselFlowProperties< DIM >::SetTimeUntilRegression().
template<unsigned DIM> bool VesselFlowProperties< DIM >::HasVesselRegressed (units::quantity< unit::time > simulationReferenceTime)
Parameters
simulationReferenceTime the reference time for the simulation
Returns
whether the vessel should regress (be removed).
Definition at line 161 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::mRegressionTime, VesselFlowProperties< DIM >::mRemoveViaRegression, and VesselFlowProperties< DIM >::mUndergoingRegression.
template<unsigned DIM> void VesselFlowProperties< DIM >::ResetRegressionTimer ()
Rescue vessel from regression.
Definition at line 274 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::mRegressionTime, VesselFlowProperties< DIM >::mRemoveViaRegression, and VesselFlowProperties< DIM >::mUndergoingRegression.
template<unsigned DIM> void VesselFlowProperties< DIM >::SetFlowRate (units::quantity< unit::flow_rate > flowRate)
Set the flow rate
Parameters
flowRate the flow rate in the segment
Definition at line 188 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
template<unsigned DIM> void VesselFlowProperties< DIM >::SetGrowthStimulus (units::quantity< unit::rate > stimulus)
Set the growth stimulus of this vessel segment
Parameters
stimulus the growth stimulus in the segment
Definition at line 233 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
template<unsigned DIM> void VesselFlowProperties< DIM >::SetHaematocrit (units::quantity< unit::dimensionless > haematocrit)
Set the haematocrit
Parameters
haematocrit the haematocrit in the segment
Definition at line 177 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
template<unsigned DIM> void VesselFlowProperties< DIM >::SetImpedance (units::quantity< unit::flow_impedance > impedance)
Set the impedance
Parameters
impedance the impedance in the segment
Definition at line 200 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
template<unsigned DIM> void VesselFlowProperties< DIM >::SetRegressionTime (units::quantity< unit::time > time)
Set dimensional time at removal of vessel from network.
Parameters
time the time at vessel removal
Definition at line 258 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::mRegressionTime, and VesselFlowProperties< DIM >::mUndergoingRegression.
template<unsigned DIM> void VesselFlowProperties< DIM >::SetTimeUntilRegression (units::quantity< unit::time > time, units::quantity< unit::time > simulationReferenceTime)
Set dimensional amount of time until removal of vessel from network.
Parameters
simulationReferenceTime the simulation reference time
time the amount of time until vessel removal
Definition at line 244 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::HasRegressionTimerStarted(), VesselFlowProperties< DIM >::mRegressionTime, VesselFlowProperties< DIM >::mRemoveViaRegression, and VesselFlowProperties< DIM >::mUndergoingRegression.
template<unsigned DIM> void VesselFlowProperties< DIM >::SetViscosity (units::quantity< unit::dynamic_viscosity > viscosity)
Set the viscosity
Parameters
viscosity the viscosity in the segment
Definition at line 211 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
template<unsigned DIM> void VesselFlowProperties< DIM >::SetWallShearStress (units::quantity< unit::pressure > wallShear)
Set the wall shear stress of this vessel segment
Parameters
wallShear the wall shear stress in the segment
Definition at line 222 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::CheckSegments(), and VesselFlowProperties< DIM >::mSegments.
template<unsigned DIM> void VesselFlowProperties< DIM >::UpdateSegments (std::vector< boost::shared_ptr< VesselSegment< DIM > > > segments)
Update the vessel segments
Parameters
segments the vessel segments
Definition at line 282 of file VesselFlowProperties.cpp.
References VesselFlowProperties< DIM >::mSegments.
Member Data Documentation
template<unsigned DIM> units::quantity<unit::time> VesselFlowProperties< DIM >::mRegressionTime private
When the vessel will be removed
Definition at line 81 of file VesselFlowProperties.hpp.
Referenced by VesselFlowProperties< DIM >::GetOutputData(), VesselFlowProperties< DIM >::GetRegressionTime(), VesselFlowProperties< DIM >::HasVesselRegressed(), VesselFlowProperties< DIM >::ResetRegressionTimer(), VesselFlowProperties< DIM >::SetRegressionTime(), and VesselFlowProperties< DIM >::SetTimeUntilRegression().
template<unsigned DIM> bool VesselFlowProperties< DIM >::mRemoveViaRegression private
Whether a vessel should be removed from the network. A vessel exists inside the network until they are removed.
Definition at line 76 of file VesselFlowProperties.hpp.
Referenced by VesselFlowProperties< DIM >::HasVesselRegressed(), VesselFlowProperties< DIM >::ResetRegressionTimer(), and VesselFlowProperties< DIM >::SetTimeUntilRegression().
template<unsigned DIM> std::vector<boost::shared_ptr<VesselSegment<DIM> > > VesselFlowProperties< DIM >::mSegments private
The vessel segments to average or sum quantities over. The Vessel class must keep this up-to-date.
Definition at line 66 of file VesselFlowProperties.hpp.
Referenced by VesselFlowProperties< DIM >::CheckSegments(), VesselFlowProperties< DIM >::GetFlowRate(), VesselFlowProperties< DIM >::GetGrowthStimulus(), VesselFlowProperties< DIM >::GetHaematocrit(), VesselFlowProperties< DIM >::GetImpedance(), VesselFlowProperties< DIM >::GetViscosity(), VesselFlowProperties< DIM >::GetWallShearStress(), VesselFlowProperties< DIM >::SetFlowRate(), VesselFlowProperties< DIM >::SetGrowthStimulus(), VesselFlowProperties< DIM >::SetHaematocrit(), VesselFlowProperties< DIM >::SetImpedance(), VesselFlowProperties< DIM >::SetViscosity(), VesselFlowProperties< DIM >::SetWallShearStress(), and VesselFlowProperties< DIM >::UpdateSegments().
template<unsigned DIM> bool VesselFlowProperties< DIM >::mUndergoingRegression private
Whether a vessel is currently undergoing regression. A vessel can be saved from this fate.
Definition at line 71 of file VesselFlowProperties.hpp.
Referenced by VesselFlowProperties< DIM >::HasRegressionTimerStarted(), VesselFlowProperties< DIM >::HasVesselRegressed(), VesselFlowProperties< DIM >::ResetRegressionTimer(), VesselFlowProperties< DIM >::SetRegressionTime(), and VesselFlowProperties< DIM >::SetTimeUntilRegression().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/vessel/properties/VesselFlowProperties.hpp
projects/MicrovesselChaste/src/population/vessel/properties/VesselFlowProperties.cpp