Chaste: VesselNetworkGenerator< DIM > Class Template Reference
VesselNetworkGenerator< DIM > Class Template Reference
Public Member Functions
VesselNetworkGenerator ()
~VesselNetworkGenerator ()
boost::shared_ptr< VesselNetwork< DIM > > GenerateParrallelNetwork (boost::shared_ptr< Part< DIM > > domain, units::quantity< unit::per_area > targetDensity, VesselDistribution::Value distrbutionType, units::quantity< unit::length > exclusionDistance=0.0 *unit::metres, bool useBbox=false, std::vector< boost::shared_ptr< DimensionalChastePoint< DIM > > > seeds=std::vector< boost::shared_ptr< DimensionalChastePoint< DIM > > >())
boost::shared_ptr< VesselNetwork< DIM > > Generate3dNetwork (boost::shared_ptr< Part< DIM > > domain, std::vector< units::quantity< unit::per_area > > targetDensity, VesselDistribution::Value distrbutionType, units::quantity< unit::length > exclusionDistance=0.0 *unit::metres, bool useBbox=false, std::vector< boost::shared_ptr< DimensionalChastePoint< DIM > > > seeds=std::vector< boost::shared_ptr< DimensionalChastePoint< DIM > > >())
boost::shared_ptr< VesselNetwork< DIM > > GenerateHexagonalNetwork (units::quantity< unit::length > width, units::quantity< unit::length > height, units::quantity< unit::length > vesselLength)
boost::shared_ptr< VesselNetwork< DIM > > GenerateHexagonalUnit (units::quantity< unit::length > vesselLength)
boost::shared_ptr< VesselNetwork< DIM > > GenerateBifurcationUnit (units::quantity< unit::length > vesselLength, DimensionalChastePoint< DIM > startPosition)
boost::shared_ptr< VesselNetwork< DIM > > GenerateSingleVessel (units::quantity< unit::length > vesselLength, DimensionalChastePoint< DIM > startPosition, unsigned divisions=0, unsigned axis=2)
boost::shared_ptr< VesselNetwork< DIM > > GenerateOvalNetwork (units::quantity< unit::length > scaleFactor, unsigned num_increments=40, double a_param=0.5, double b_param=1.0)
boost::shared_ptr< VesselNetwork< DIM > > GenerateFromPart (boost::shared_ptr< Part< DIM > > part)
boost::shared_ptr< VesselNetwork< DIM > > GenerateVoronoiNetwork (units::quantity< unit::length > cubeX, units::quantity< unit::length > cubeY, units::quantity< unit::length > cubeZ, unsigned numPoints=400)
void PatternUnitByTranslation (boost::shared_ptr< VesselNetwork< DIM > > pInputUnit, std::vector< unsigned > numberOfUnits)
void MapToSphere (boost::shared_ptr< VesselNetwork< DIM > > pInputUnit, units::quantity< unit::length > radius, units::quantity< unit::length > thickess, double azimuthExtent, double polarExtent)
void SetReferenceLengthScale (units::quantity< unit::length > rReferenceLength)
Private Attributes
units::quantity< unit::length > mReferenceLength
Detailed Description
template<unsigned DIM>
class VesselNetworkGenerator< DIM >
Definition at line 70 of file VesselNetworkGenerator.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VesselNetworkGenerator< DIM >::VesselNetworkGenerator ()
Constructor
Definition at line 46 of file VesselNetworkGenerator.cpp.
template<unsigned DIM> VesselNetworkGenerator< DIM >::~VesselNetworkGenerator ()
Destructor
Definition at line 52 of file VesselNetworkGenerator.cpp.
Member Function Documentation
template<unsigned DIM> void VesselNetworkGenerator< DIM >::SetReferenceLengthScale (units::quantity< unit::length > rReferenceLength)
Set the reference length scale
Parameters
rLengthScale the reference length scale
Definition at line 57 of file VesselNetworkGenerator.cpp.
References Part< DIM >::Create(), VesselNetwork< DIM >::Create(), Vessel< DIM >::Create(), VoronoiGenerator< DIM >::Generate(), DimensionalChastePoint< DIM >::GetLocation(), and VesselNetworkGenerator< DIM >::mReferenceLength.
Member Data Documentation
template<unsigned DIM> units::quantity<unit::length> VesselNetworkGenerator< DIM >::mReferenceLength private
The reference length scale for the vessel network, default in microns.
Definition at line 76 of file VesselNetworkGenerator.hpp.
Referenced by VesselNetworkGenerator< DIM >::SetReferenceLengthScale().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/vessel/generators/VesselNetworkGenerator.hpp
projects/MicrovesselChaste/src/population/vessel/generators/VesselNetworkGenerator.cpp