Chaste: LQRadiotherapyCellKiller< DIM > Class Template Reference
LQRadiotherapyCellKiller< DIM > Class Template Reference
#include <LQRadiotherapyCellKiller.hpp>
Public Member Functions
LQRadiotherapyCellKiller (AbstractCellPopulation< DIM > *pCellPopulation)
void CheckAndLabelSingleCellForApoptosis (CellPtr pCell)
void CheckAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
void SetDoseInjected (units::quantity< unit::absorbed_dose > d)
void SetTimeOfRadiation (std::vector< units::quantity< unit::time > > t)
void SetCancerousRadiosensitivity (units::quantity< unit::per_absorbed_dose > alpha, units::quantity< unit::per_absorbed_dose_squared > beta)
void SetNormalRadiosensitivity (units::quantity< unit::per_absorbed_dose > alpha, units::quantity< unit::per_absorbed_dose_squared > beta)
void SetOerAlphaMax (double value)
void SetOerAlphaMin (double value)
void SetOerBetaMax (double value)
void SetOerBetaMin (double value)
void SetOerConstant (double value)
void SetAlphaMax (units::quantity< unit::per_absorbed_dose > value)
void SetBetaMax (units::quantity< unit::per_absorbed_dose_squared > value)
void UseOer (bool useOer)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
units::quantity< unit::per_absorbed_dose > cancerousLinearRadiosensitivity
units::quantity< unit::per_absorbed_dose_squared > cancerousQuadraticRadiosensitivity
units::quantity< unit::per_absorbed_dose > normalLinearRadiosensitivity
units::quantity< unit::per_absorbed_dose_squared > normalQuadraticRadiosensitivity
units::quantity< unit::absorbed_dose > mDose
std::vector< units::quantity< unit::time > > mRadiationTimes
double mOerAlphaMax
double mOerAlphaMin
double mOerBetaMax
double mOerBetaMin
double mKOer
units::quantity< unit::per_absorbed_dose > mAlphaMax
units::quantity< unit::per_absorbed_dose_squared > mBetaMax
bool mUseOer
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class LQRadiotherapyCellKiller< DIM >
A radiotherapy based cell killer based on the linear-quadratic model. Some different OER models are included.
Definition at line 51 of file LQRadiotherapyCellKiller.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> LQRadiotherapyCellKiller< DIM >::LQRadiotherapyCellKiller (AbstractCellPopulation< DIM > * pCellPopulation)
Default constructor.
Parameters
pCellPopulation pointer to the cell population
Definition at line 42 of file LQRadiotherapyCellKiller.cpp.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
Member Function Documentation
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath ()
Loop over cells and start apoptosis randomly, based on the user-set probability.
Definition at line 180 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis().
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis (CellPtr pCell)
Overridden method to test a given cell for apoptosis.
Parameters
pCell the cell to test for apoptosis
Definition at line 139 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::cancerousLinearRadiosensitivity, LQRadiotherapyCellKiller< DIM >::cancerousQuadraticRadiosensitivity, BaseUnits::GetReferenceTimeScale(), BaseUnits::Instance(), LQRadiotherapyCellKiller< DIM >::mAlphaMax, LQRadiotherapyCellKiller< DIM >::mBetaMax, LQRadiotherapyCellKiller< DIM >::mDose, LQRadiotherapyCellKiller< DIM >::mKOer, LQRadiotherapyCellKiller< DIM >::mOerAlphaMax, LQRadiotherapyCellKiller< DIM >::mOerAlphaMin, LQRadiotherapyCellKiller< DIM >::mOerBetaMax, LQRadiotherapyCellKiller< DIM >::mOerBetaMin, LQRadiotherapyCellKiller< DIM >::mRadiationTimes, and LQRadiotherapyCellKiller< DIM >::mUseOer.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), and LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile)
Overridden OutputCellKillerParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Definition at line 190 of file LQRadiotherapyCellKiller.cpp.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> template<class Archive > void LQRadiotherapyCellKiller< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the object.
Parameters
archive the archive
version the current version of this class
Definition at line 134 of file LQRadiotherapyCellKiller.hpp.
References LQRadiotherapyCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), LQRadiotherapyCellKiller< DIM >::LQRadiotherapyCellKiller(), LQRadiotherapyCellKiller< DIM >::OutputCellKillerParameters(), LQRadiotherapyCellKiller< DIM >::SetAlphaMax(), LQRadiotherapyCellKiller< DIM >::SetBetaMax(), LQRadiotherapyCellKiller< DIM >::SetCancerousRadiosensitivity(), LQRadiotherapyCellKiller< DIM >::SetDoseInjected(), LQRadiotherapyCellKiller< DIM >::SetNormalRadiosensitivity(), LQRadiotherapyCellKiller< DIM >::SetOerAlphaMax(), LQRadiotherapyCellKiller< DIM >::SetOerAlphaMin(), LQRadiotherapyCellKiller< DIM >::SetOerBetaMax(), LQRadiotherapyCellKiller< DIM >::SetOerBetaMin(), LQRadiotherapyCellKiller< DIM >::SetOerConstant(), LQRadiotherapyCellKiller< DIM >::SetTimeOfRadiation(), and LQRadiotherapyCellKiller< DIM >::UseOer().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetAlphaMax (units::quantity< unit::per_absorbed_dose > value)
Sets alpha_max radiotherapy value
Parameters
value alpha_max radiotherapy value
Definition at line 105 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mAlphaMax.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetBetaMax (units::quantity< unit::per_absorbed_dose_squared > value)
Sets beta_max radiotherapy value
Parameters
value beta_max radiotherapy value
Definition at line 111 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mBetaMax.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetCancerousRadiosensitivity (units::quantity< unit::per_absorbed_dose > alpha, units::quantity< unit::per_absorbed_dose_squared > beta)
Sets cancerousLinearRadiosensitivity and cancerousQuadraticRadiosensitivity to specified concentration.
Parameters
alpha linear radiosensitivity for cancer cells
beta quadratic radiosensitivity for cancer cells
Definition at line 123 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::cancerousLinearRadiosensitivity, and LQRadiotherapyCellKiller< DIM >::cancerousQuadraticRadiosensitivity.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetDoseInjected (units::quantity< unit::absorbed_dose > d)
Sets doseInjected, the radiation dose injected
Parameters
d dose delivered
Definition at line 63 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mDose.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetNormalRadiosensitivity (units::quantity< unit::per_absorbed_dose > alpha, units::quantity< unit::per_absorbed_dose_squared > beta)
Sets normalLinearRadiosensitivity and normalQuadraticRadiosensitivity to specified concentration.
Parameters
alpha linear radiosensitivity for normal cells
beta quadratic radiosensitivity for normal cells
Definition at line 131 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::normalLinearRadiosensitivity, and LQRadiotherapyCellKiller< DIM >::normalQuadraticRadiosensitivity.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetOerAlphaMax (double value)
Sets alpha_max OER value
Parameters
value alpha_max OER value
Definition at line 75 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mOerAlphaMax.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetOerAlphaMin (double value)
Sets alpha_min OER value
Parameters
value alpha_min OER value
Definition at line 81 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mOerAlphaMin.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetOerBetaMax (double value)
Sets beta_max OER value
Parameters
value beta_max OER value
Definition at line 87 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mOerBetaMax.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetOerBetaMin (double value)
Sets beta_min OER value
Parameters
value beta_min OER value
Definition at line 93 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mOerBetaMin.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetOerConstant (double value)
Sets K OER value
Parameters
value K OER value
Definition at line 99 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mKOer.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::SetTimeOfRadiation (std::vector< units::quantity< unit::time > > t)
Sets timeOfRadiation, the time at which radiation occurs
Parameters
t the radiation times
Definition at line 69 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mRadiationTimes.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
template<unsigned DIM> void LQRadiotherapyCellKiller< DIM >::UseOer (bool useOer)
Whether to use OER
Parameters
useOer Whether to use OER
Definition at line 117 of file LQRadiotherapyCellKiller.cpp.
References LQRadiotherapyCellKiller< DIM >::mUseOer.
Referenced by LQRadiotherapyCellKiller< DIM >::serialize().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 126 of file LQRadiotherapyCellKiller.hpp.
Member Data Documentation
template<unsigned DIM> units::quantity<unit::per_absorbed_dose> LQRadiotherapyCellKiller< DIM >::cancerousLinearRadiosensitivity private
Linear component of radiosensitivity of a cancerous cell.
Definition at line 56 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetCancerousRadiosensitivity().
template<unsigned DIM> units::quantity<unit::per_absorbed_dose_squared> LQRadiotherapyCellKiller< DIM >::cancerousQuadraticRadiosensitivity private
Quadratic component of radiosensitivity of a cancerous cell.
Definition at line 61 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetCancerousRadiosensitivity().
template<unsigned DIM> units::quantity<unit::per_absorbed_dose> LQRadiotherapyCellKiller< DIM >::mAlphaMax private
Radiotherapy alpha_max term
Definition at line 111 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetAlphaMax().
template<unsigned DIM> units::quantity<unit::per_absorbed_dose_squared> LQRadiotherapyCellKiller< DIM >::mBetaMax private
Radiotherapy beta_max term
Definition at line 116 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetBetaMax().
template<unsigned DIM> units::quantity<unit::absorbed_dose> LQRadiotherapyCellKiller< DIM >::mDose private
Dose of Radiation injected
Definition at line 76 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetDoseInjected().
template<unsigned DIM> double LQRadiotherapyCellKiller< DIM >::mKOer private
Oer constant K term
Definition at line 106 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetOerConstant().
template<unsigned DIM> double LQRadiotherapyCellKiller< DIM >::mOerAlphaMax private
alpha_max OER term
Definition at line 86 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetOerAlphaMax().
template<unsigned DIM> double LQRadiotherapyCellKiller< DIM >::mOerAlphaMin private
alpha_min OER term
Definition at line 91 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetOerAlphaMin().
template<unsigned DIM> double LQRadiotherapyCellKiller< DIM >::mOerBetaMax private
beta_max OER term
Definition at line 96 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetOerBetaMax().
template<unsigned DIM> double LQRadiotherapyCellKiller< DIM >::mOerBetaMin private
beta_min OER term
Definition at line 101 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetOerBetaMin().
template<unsigned DIM> std::vector<units::quantity<unit::time> > LQRadiotherapyCellKiller< DIM >::mRadiationTimes private
Times at which radiotherapy is used
Definition at line 81 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::SetTimeOfRadiation().
template<unsigned DIM> bool LQRadiotherapyCellKiller< DIM >::mUseOer private
Whether to use an oxygen enhancement ratio
Definition at line 121 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), and LQRadiotherapyCellKiller< DIM >::UseOer().
template<unsigned DIM> units::quantity<unit::per_absorbed_dose> LQRadiotherapyCellKiller< DIM >::normalLinearRadiosensitivity private
Linear component of radiosensitivity of a normal cell.
Definition at line 66 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::SetNormalRadiosensitivity().
template<unsigned DIM> units::quantity<unit::per_absorbed_dose_squared> LQRadiotherapyCellKiller< DIM >::normalQuadraticRadiosensitivity private
Quadratic component of radiosensitivity of a normal cell.
Definition at line 71 of file LQRadiotherapyCellKiller.hpp.
Referenced by LQRadiotherapyCellKiller< DIM >::SetNormalRadiosensitivity().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/cell/killers/LQRadiotherapyCellKiller.hpp
projects/MicrovesselChaste/src/population/cell/killers/LQRadiotherapyCellKiller.cpp