Chaste: CellPopulationMigrationRule< DIM > Class Template Reference
CellPopulationMigrationRule< DIM > Class Template Reference
#include <CellPopulationMigrationRule.hpp>
Public Member Functions
CellPopulationMigrationRule ()
virtual ~CellPopulationMigrationRule ()
virtual std::vector< int > GetIndices (const std::vector< boost::shared_ptr< VesselNode< DIM > > > &rNodes)
void SetVolumeFraction (boost::shared_ptr< AbstractCellMutationState > mutation_state, double volume_fraction)
double GetOccupyingVolumeFraction (boost::shared_ptr< AbstractCellMutationState > mutation_state)
Public Member Functions inherited from LatticeBasedMigrationRule< DIM >
LatticeBasedMigrationRule ()
virtual ~LatticeBasedMigrationRule ()
void SetMovementProbability (double movementProbability)
Public Member Functions inherited from AbstractMigrationRule< DIM >
AbstractMigrationRule ()
virtual ~AbstractMigrationRule ()
virtual std::vector< DimensionalChastePoint< DIM > > GetDirections (const std::vector< boost::shared_ptr< VesselNode< DIM > > > &rNodes)
void SetIsSprouting (bool isSprouting=true)
void SetDiscreteContinuumSolver (boost::shared_ptr< AbstractDiscreteContinuumSolver< DIM > > pSolver)
void SetNetwork (boost::shared_ptr< VesselNetwork< DIM > > pNetwork)
void SetBoundingDomain (boost::shared_ptr< Part< DIM > > pPart)
void SetGrid (boost::shared_ptr< RegularGrid< DIM > > pGrid)
void SetCellPopulation (boost::shared_ptr< AbstractCellPopulation< DIM > > pCellPopulation)
Static Public Member Functions
static boost::shared_ptr< CellPopulationMigrationRule< DIM > > Create ()
Static Public Member Functions inherited from LatticeBasedMigrationRule< DIM >
static boost::shared_ptr< LatticeBasedMigrationRule< DIM > > Create ()
Static Public Member Functions inherited from AbstractMigrationRule< DIM >
static boost::shared_ptr< AbstractMigrationRule< DIM > > Create ()
Protected Member Functions
virtual std::vector< double > GetNeighbourMovementProbabilities (boost::shared_ptr< VesselNode< DIM > > pNode, std::vector< unsigned > neighbourIndices, unsigned gridIndex)
Protected Member Functions inherited from LatticeBasedMigrationRule< DIM >
virtual int GetNeighbourMovementIndex (std::vector< double > movementProbabilities, std::vector< unsigned > neighbourIndices)
Protected Attributes
std::map< boost::shared_ptr< AbstractCellMutationState >, double > mVolumeFractionMap
std::vector< std::vector< CellPtr > > mPointCellMap
Protected Attributes inherited from LatticeBasedMigrationRule< DIM >
double mMovementProbability
Protected Attributes inherited from AbstractMigrationRule< DIM >
boost::shared_ptr< AbstractDiscreteContinuumSolver< DIM > > mpSolver
boost::shared_ptr< VesselNetwork< DIM > > mpVesselNetwork
bool mIsSprouting
boost::shared_ptr< AbstractCellPopulation< DIM > > mpCellPopulation
boost::shared_ptr< RegularGrid< DIM > > mpGrid
boost::shared_ptr< Part< DIM > > mpBoundingDomain
Detailed Description
template<unsigned DIM>
class CellPopulationMigrationRule< DIM >
A simple random direction lattice based migration rule. Not physical, but useful for code testing.
Definition at line 51 of file CellPopulationMigrationRule.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> CellPopulationMigrationRule< DIM >::CellPopulationMigrationRule ()
Constructor.
Definition at line 41 of file CellPopulationMigrationRule.cpp.
template<unsigned DIM> CellPopulationMigrationRule< DIM >::~CellPopulationMigrationRule () virtual
Destructor.
Definition at line 57 of file CellPopulationMigrationRule.cpp.
Member Function Documentation
template<unsigned DIM> boost::shared_ptr< CellPopulationMigrationRule< DIM > > CellPopulationMigrationRule< DIM >::Create () static
Construct a new instance of the class and return a shared pointer to it.
Returns
a pointer to a new instance of the class
Definition at line 50 of file CellPopulationMigrationRule.cpp.
template<unsigned DIM> std::vector< int > CellPopulationMigrationRule< DIM >::GetIndices (const std::vector< boost::shared_ptr< VesselNode< DIM > > > & rNodes) virtual
Calculate the grid index that each migrating node will move into. Set to -1 if the node does not move.
Parameters
rNodes nodes to calculate indices
Returns
a vector of grid indices to move nodes into
Reimplemented from LatticeBasedMigrationRule< DIM >.
Definition at line 156 of file CellPopulationMigrationRule.cpp.
References LatticeBasedMigrationRule< DIM >::GetNeighbourMovementIndex(), CellPopulationMigrationRule< DIM >::GetNeighbourMovementProbabilities(), AbstractMigrationRule< DIM >::mpCellPopulation, AbstractMigrationRule< DIM >::mpGrid, CellPopulationMigrationRule< DIM >::mPointCellMap, and AbstractMigrationRule< DIM >::mpVesselNetwork.
template<unsigned DIM> std::vector< double > CellPopulationMigrationRule< DIM >::GetNeighbourMovementProbabilities (boost::shared_ptr< VesselNode< DIM > > pNode, std::vector< unsigned > neighbourIndices, unsigned gridIndex) protected virtual
Get the probabilities for movement into each lattice point in the node's neighbourhood. This can be over-written for custom movement rules.
Parameters
pNode the sprouting node
neighbourIndices the grid indices of the neighbour nodes
gridIndex the current grid index
Returns
a vector of movement probabilities corresponding to each neighbour index
Reimplemented from LatticeBasedMigrationRule< DIM >.
Definition at line 105 of file CellPopulationMigrationRule.cpp.
References CellPopulationMigrationRule< DIM >::GetOccupyingVolumeFraction(), LatticeBasedMigrationRule< DIM >::mMovementProbability, AbstractMigrationRule< DIM >::mpGrid, and CellPopulationMigrationRule< DIM >::mPointCellMap.
Referenced by CellPopulationMigrationRule< DIM >::GetIndices().
template<unsigned DIM> double CellPopulationMigrationRule< DIM >::GetOccupyingVolumeFraction (boost::shared_ptr< AbstractCellMutationState > mutation_state)
Return occupying volume fraction for particular type of cell.
Parameters
mutation_state the cell muatation state
Returns
the occupying fraction
Definition at line 88 of file CellPopulationMigrationRule.cpp.
References CellPopulationMigrationRule< DIM >::mVolumeFractionMap.
Referenced by CellPopulationMigrationRule< DIM >::GetNeighbourMovementProbabilities().
template<unsigned DIM> void CellPopulationMigrationRule< DIM >::SetVolumeFraction (boost::shared_ptr< AbstractCellMutationState > mutation_state, double volume_fraction)
Method to set volume fraction for particular type of cell.
Parameters
mutation_state the cell muatation state
volume_fraction the occupying fraction
Definition at line 63 of file CellPopulationMigrationRule.cpp.
References CellPopulationMigrationRule< DIM >::mVolumeFractionMap.
Member Data Documentation
template<unsigned DIM> std::vector<std::vector<CellPtr> > CellPopulationMigrationRule< DIM >::mPointCellMap protected
Collection of cells at each lattice point
Definition at line 64 of file CellPopulationMigrationRule.hpp.
Referenced by CellPopulationMigrationRule< DIM >::GetIndices(), and CellPopulationMigrationRule< DIM >::GetNeighbourMovementProbabilities().
template<unsigned DIM> std::map<boost::shared_ptr<AbstractCellMutationState> , double > CellPopulationMigrationRule< DIM >::mVolumeFractionMap protected
Volume fraction of a lattice site that each cell will occupy
Definition at line 59 of file CellPopulationMigrationRule.hpp.
Referenced by CellPopulationMigrationRule< DIM >::GetOccupyingVolumeFraction(), and CellPopulationMigrationRule< DIM >::SetVolumeFraction().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/simulation/angiogenesis/migration_rules/lattice/CellPopulationMigrationRule.hpp
projects/MicrovesselChaste/src/simulation/angiogenesis/migration_rules/lattice/CellPopulationMigrationRule.cpp