Chaste: VesselNetworkGraphCalculator< DIM > Class Template Reference
VesselNetworkGraphCalculator< DIM > Class Template Reference
#include <VesselNetworkGraphCalculator.hpp>
Public Member Functions
VesselNetworkGraphCalculator ()
~VesselNetworkGraphCalculator ()
void SetVesselNetwork (boost::shared_ptr< VesselNetwork< DIM > > pVesselNetwork)
std::vector< std::vector< unsigned > > GetNodeNodeConnectivity ()
std::vector< std::vector< unsigned > > GetNodeVesselConnectivity ()
bool IsConnected (boost::shared_ptr< VesselNode< DIM > > pSourceNode, boost::shared_ptr< VesselNode< DIM > > pQueryNode)
std::vector< bool > IsConnected (std::vector< boost::shared_ptr< VesselNode< DIM > > > sourceNodes, std::vector< boost::shared_ptr< VesselNode< DIM > > > queryNodes)
void WriteConnectivity (const std::string &rFilename)
Static Public Member Functions
static boost::shared_ptr< VesselNetworkGraphCalculator< DIM > > Create ()
Private Attributes
boost::shared_ptr< VesselNetwork< DIM > > mpVesselNetwork
Detailed Description
template<unsigned DIM>
class VesselNetworkGraphCalculator< DIM >
Calculate graph properties of vessel networks
Definition at line 47 of file VesselNetworkGraphCalculator.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VesselNetworkGraphCalculator< DIM >::VesselNetworkGraphCalculator ()
Constructor
Definition at line 91 of file VesselNetworkGraphCalculator.cpp.
template<unsigned DIM> VesselNetworkGraphCalculator< DIM >::~VesselNetworkGraphCalculator ()
Destructor
Definition at line 98 of file VesselNetworkGraphCalculator.cpp.
Member Function Documentation
template<unsigned DIM> boost::shared_ptr< VesselNetworkGraphCalculator< DIM > > VesselNetworkGraphCalculator< DIM >::Create () static
Construct a new instance of the class and return a shared pointer to it.
Returns
a pointer to the class instance
Definition at line 104 of file VesselNetworkGraphCalculator.cpp.
Referenced by FlowSolver< DIM >::SetUp().
template<unsigned DIM> std::vector< std::vector< unsigned > > VesselNetworkGraphCalculator< DIM >::GetNodeNodeConnectivity ()
Return the indices of each node attached to a node
Returns
the node-node connectivity
Definition at line 111 of file VesselNetworkGraphCalculator.cpp.
References VesselNetworkGraphCalculator< DIM >::GetNodeVesselConnectivity(), and VesselNetworkGraphCalculator< DIM >::mpVesselNetwork.
template<unsigned DIM> std::vector< std::vector< unsigned > > VesselNetworkGraphCalculator< DIM >::GetNodeVesselConnectivity ()
Return the indices of each vessel attached to a node
Returns
the indices of each vessel attached to a node
Definition at line 144 of file VesselNetworkGraphCalculator.cpp.
References VesselNetworkGraphCalculator< DIM >::mpVesselNetwork.
Referenced by VesselNetworkGraphCalculator< DIM >::GetNodeNodeConnectivity().
template<unsigned DIM> bool VesselNetworkGraphCalculator< DIM >::IsConnected (boost::shared_ptr< VesselNode< DIM > > pSourceNode, boost::shared_ptr< VesselNode< DIM > > pQueryNode)
Return whether a node is connected to a source node.
Parameters
pSourceNode the source node
pQueryNode the query node
Returns
whether a node is connected to a source node.
Definition at line 176 of file VesselNetworkGraphCalculator.cpp.
References VesselNetworkGraphCalculator< DIM >::mpVesselNetwork.
template<unsigned DIM> std::vector< bool > VesselNetworkGraphCalculator< DIM >::IsConnected (std::vector< boost::shared_ptr< VesselNode< DIM > > > sourceNodes, std::vector< boost::shared_ptr< VesselNode< DIM > > > queryNodes)
Return whether a vector of nodes is connected to a vector of source nodes.
Parameters
sourceNodes the source nodes
queryNodes the query nodes
Returns
whether a node is connected to a source node.
Definition at line 249 of file VesselNetworkGraphCalculator.cpp.
References VesselNetworkGraphCalculator< DIM >::mpVesselNetwork.
template<unsigned DIM> void VesselNetworkGraphCalculator< DIM >::SetVesselNetwork (boost::shared_ptr< VesselNetwork< DIM > > pVesselNetwork)
Set the vessel network
Parameters
pVesselNetwork the vessel network
Definition at line 381 of file VesselNetworkGraphCalculator.cpp.
References VesselNetworkGraphCalculator< DIM >::mpVesselNetwork.
template<unsigned DIM> void VesselNetworkGraphCalculator< DIM >::WriteConnectivity (const std::string & rFilename)
Outputs connectivity of vessels to file in graphviz format (.gv).
Parameters
rFilename the output filename
Definition at line 336 of file VesselNetworkGraphCalculator.cpp.
References VesselNetworkGraphCalculator< DIM >::mpVesselNetwork.
Member Data Documentation
template<unsigned DIM> boost::shared_ptr<VesselNetwork<DIM> > VesselNetworkGraphCalculator< DIM >::mpVesselNetwork private
Container for the VesselNetwork.
Definition at line 55 of file VesselNetworkGraphCalculator.hpp.
Referenced by VesselNetworkGraphCalculator< DIM >::GetNodeNodeConnectivity(), VesselNetworkGraphCalculator< DIM >::GetNodeVesselConnectivity(), VesselNetworkGraphCalculator< DIM >::IsConnected(), VesselNetworkGraphCalculator< DIM >::SetVesselNetwork(), and VesselNetworkGraphCalculator< DIM >::WriteConnectivity().
The documentation for this class was generated from the following files:
projects/MicrovesselChaste/src/population/vessel/calculators/VesselNetworkGraphCalculator.hpp
projects/MicrovesselChaste/src/population/vessel/calculators/VesselNetworkGraphCalculator.cpp