#ifndef VesselNetworkActorGenerator3_hpp__pyplusplus_wrapper
#define VesselNetworkActorGenerator3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_VesselNetworkActorGenerator3_class(py::module &m);
#endif // VesselNetworkActorGenerator3_hpp__pyplusplus_wrapper
