#ifndef AbstractVesselNetworkCalculator3_hpp__pyplusplus_wrapper
#define AbstractVesselNetworkCalculator3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractVesselNetworkCalculator3_class(py::module &m);
#endif // AbstractVesselNetworkCalculator3_hpp__pyplusplus_wrapper
