#ifndef AbstractStructuralAdaptationSolver2_hpp__pyplusplus_wrapper
#define AbstractStructuralAdaptationSolver2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractStructuralAdaptationSolver2_class(py::module &m);
#endif // AbstractStructuralAdaptationSolver2_hpp__pyplusplus_wrapper
