#ifndef AbstractVesselNetworkCalculator2_hpp__pyplusplus_wrapper
#define AbstractVesselNetworkCalculator2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractVesselNetworkCalculator2_class(py::module &m);
#endif // AbstractVesselNetworkCalculator2_hpp__pyplusplus_wrapper
