// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "AlarconHaematocritSolver2.pypp.hpp"

namespace bp = boost::python;

struct AlarconHaematocritSolver_less__2__greater__wrapper : AlarconHaematocritSolver< 2 >, bp::wrapper< AlarconHaematocritSolver< 2 > > {

    AlarconHaematocritSolver_less__2__greater__wrapper(AlarconHaematocritSolver<2> const & arg )
    : AlarconHaematocritSolver<2>( arg )
      , bp::wrapper< AlarconHaematocritSolver< 2 > >(){
        // copy constructor
        
    }

    AlarconHaematocritSolver_less__2__greater__wrapper( )
    : AlarconHaematocritSolver<2>( )
      , bp::wrapper< AlarconHaematocritSolver< 2 > >(){
        // null constructor
    
    }

    virtual void Calculate(  ) {
        if( bp::override func_Calculate = this->get_override( "Calculate" ) )
            func_Calculate(  );
        else{
            this->AlarconHaematocritSolver< 2 >::Calculate(  );
        }
    }
    
    void default_Calculate(  ) {
        AlarconHaematocritSolver< 2 >::Calculate( );
    }

};

void register_AlarconHaematocritSolver2_class(){

    { //::AlarconHaematocritSolver< 2 >
        typedef bp::class_< AlarconHaematocritSolver_less__2__greater__wrapper, bp::bases< AbstractHaematocritSolver< 2 > > > AlarconHaematocritSolver2_exposer_t;
        AlarconHaematocritSolver2_exposer_t AlarconHaematocritSolver2_exposer = AlarconHaematocritSolver2_exposer_t( "AlarconHaematocritSolver2", bp::init< >() );
        bp::scope AlarconHaematocritSolver2_scope( AlarconHaematocritSolver2_exposer );
        { //::AlarconHaematocritSolver< 2 >::Calculate
        
            typedef AlarconHaematocritSolver< 2 > exported_class_t;
            typedef void ( exported_class_t::*Calculate_function_type)(  ) ;
            typedef void ( AlarconHaematocritSolver_less__2__greater__wrapper::*default_Calculate_function_type)(  ) ;
            
            AlarconHaematocritSolver2_exposer.def( 
                "Calculate"
                , Calculate_function_type(&::AlarconHaematocritSolver< 2 >::Calculate)
                , default_Calculate_function_type(&AlarconHaematocritSolver_less__2__greater__wrapper::default_Calculate) );
        
        }
        { //::AlarconHaematocritSolver< 2 >::Create
        
            typedef AlarconHaematocritSolver< 2 > exported_class_t;
            typedef ::boost::shared_ptr< AlarconHaematocritSolver< 2 > > ( *Create_function_type )(  );
            
            AlarconHaematocritSolver2_exposer.def( 
                "Create"
                , Create_function_type( &::AlarconHaematocritSolver< 2 >::Create ) );
        
        }
        { //::AlarconHaematocritSolver< 2 >::SetAlpha
        
            typedef AlarconHaematocritSolver< 2 > exported_class_t;
            typedef void ( exported_class_t::*SetAlpha_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::dimensionless_type, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            AlarconHaematocritSolver2_exposer.def( 
                "SetAlpha"
                , SetAlpha_function_type( &::AlarconHaematocritSolver< 2 >::SetAlpha )
                , ( bp::arg("alpha") ) );
        
        }
        { //::AlarconHaematocritSolver< 2 >::SetHaematocrit
        
            typedef AlarconHaematocritSolver< 2 > exported_class_t;
            typedef void ( exported_class_t::*SetHaematocrit_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::dimensionless_type, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            AlarconHaematocritSolver2_exposer.def( 
                "SetHaematocrit"
                , SetHaematocrit_function_type( &::AlarconHaematocritSolver< 2 >::SetHaematocrit )
                , ( bp::arg("haematocrit") ) );
        
        }
        { //::AlarconHaematocritSolver< 2 >::SetTHR
        
            typedef AlarconHaematocritSolver< 2 > exported_class_t;
            typedef void ( exported_class_t::*SetTHR_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::dimensionless_type, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            AlarconHaematocritSolver2_exposer.def( 
                "SetTHR"
                , SetTHR_function_type( &::AlarconHaematocritSolver< 2 >::SetTHR )
                , ( bp::arg("thr") ) );
        
        }
        AlarconHaematocritSolver2_exposer.staticmethod( "Create" );
        bp::register_ptr_to_python< boost::shared_ptr< AlarconHaematocritSolver<2> > >();
        bp::implicitly_convertible< boost::shared_ptr< AlarconHaematocritSolver< 2 > >, boost::shared_ptr< AbstractHaematocritSolver< 2 > > >();
        bp::implicitly_convertible< boost::shared_ptr< AlarconHaematocritSolver< 2 > >, boost::shared_ptr< AbstractVesselNetworkCalculator< 2 > > >();
    }

}
