#ifndef BetteridgeHaematocritSolver3_hpp__pyplusplus_wrapper
#define BetteridgeHaematocritSolver3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_BetteridgeHaematocritSolver3_class(py::module &m);
#endif // BetteridgeHaematocritSolver3_hpp__pyplusplus_wrapper
