#ifndef MechanicalStimulusCalculator3_hpp__pyplusplus_wrapper
#define MechanicalStimulusCalculator3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_MechanicalStimulusCalculator3_class(py::module &m);
#endif // MechanicalStimulusCalculator3_hpp__pyplusplus_wrapper
