// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "MechanicalStimulusCalculator3.pypp.hpp"

namespace bp = boost::python;

struct MechanicalStimulusCalculator_less__3__greater__wrapper : MechanicalStimulusCalculator< 3 >, bp::wrapper< MechanicalStimulusCalculator< 3 > > {

    MechanicalStimulusCalculator_less__3__greater__wrapper(MechanicalStimulusCalculator<3> const & arg )
    : MechanicalStimulusCalculator<3>( arg )
      , bp::wrapper< MechanicalStimulusCalculator< 3 > >(){
        // copy constructor
        
    }

    MechanicalStimulusCalculator_less__3__greater__wrapper( )
    : MechanicalStimulusCalculator<3>( )
      , bp::wrapper< MechanicalStimulusCalculator< 3 > >(){
        // null constructor
    
    }

    virtual void Calculate(  ) {
        if( bp::override func_Calculate = this->get_override( "Calculate" ) )
            func_Calculate(  );
        else{
            this->MechanicalStimulusCalculator< 3 >::Calculate(  );
        }
    }
    
    void default_Calculate(  ) {
        MechanicalStimulusCalculator< 3 >::Calculate( );
    }

};

void register_MechanicalStimulusCalculator3_class(){

    { //::MechanicalStimulusCalculator< 3 >
        typedef bp::class_< MechanicalStimulusCalculator_less__3__greater__wrapper, bp::bases< AbstractVesselNetworkCalculator< 3 > > > MechanicalStimulusCalculator3_exposer_t;
        MechanicalStimulusCalculator3_exposer_t MechanicalStimulusCalculator3_exposer = MechanicalStimulusCalculator3_exposer_t( "MechanicalStimulusCalculator3", bp::init< >() );
        bp::scope MechanicalStimulusCalculator3_scope( MechanicalStimulusCalculator3_exposer );
        { //::MechanicalStimulusCalculator< 3 >::Calculate
        
            typedef MechanicalStimulusCalculator< 3 > exported_class_t;
            typedef void ( exported_class_t::*Calculate_function_type)(  ) ;
            typedef void ( MechanicalStimulusCalculator_less__3__greater__wrapper::*default_Calculate_function_type)(  ) ;
            
            MechanicalStimulusCalculator3_exposer.def( 
                "Calculate"
                , Calculate_function_type(&::MechanicalStimulusCalculator< 3 >::Calculate)
                , default_Calculate_function_type(&MechanicalStimulusCalculator_less__3__greater__wrapper::default_Calculate) );
        
        }
        { //::MechanicalStimulusCalculator< 3 >::Create
        
            typedef MechanicalStimulusCalculator< 3 > exported_class_t;
            typedef ::boost::shared_ptr< MechanicalStimulusCalculator< 3 > > ( *Create_function_type )(  );
            
            MechanicalStimulusCalculator3_exposer.def( 
                "Create"
                , Create_function_type( &::MechanicalStimulusCalculator< 3 >::Create ) );
        
        }
        { //::MechanicalStimulusCalculator< 3 >::GetTauP
        
            typedef MechanicalStimulusCalculator< 3 > exported_class_t;
            typedef ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< -1, 1 > >, boost::units::list< boost::units::dim< boost::units::mass_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::list< boost::units::dim< boost::units::time_base_dimension, boost::units::static_rational< -2, 1 > >, boost::units::dimensionless_type > > >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ( exported_class_t::*GetTauP_function_type)(  ) ;
            
            MechanicalStimulusCalculator3_exposer.def( 
                "GetTauP"
                , GetTauP_function_type( &::MechanicalStimulusCalculator< 3 >::GetTauP ) );
        
        }
        { //::MechanicalStimulusCalculator< 3 >::GetTauReference
        
            typedef MechanicalStimulusCalculator< 3 > exported_class_t;
            typedef ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< -1, 1 > >, boost::units::list< boost::units::dim< boost::units::mass_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::list< boost::units::dim< boost::units::time_base_dimension, boost::units::static_rational< -2, 1 > >, boost::units::dimensionless_type > > >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ( exported_class_t::*GetTauReference_function_type)(  ) ;
            
            MechanicalStimulusCalculator3_exposer.def( 
                "GetTauReference"
                , GetTauReference_function_type( &::MechanicalStimulusCalculator< 3 >::GetTauReference ) );
        
        }
        { //::MechanicalStimulusCalculator< 3 >::SetTauP
        
            typedef MechanicalStimulusCalculator< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetTauP_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< -1, 1 > >, boost::units::list< boost::units::dim< boost::units::mass_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::list< boost::units::dim< boost::units::time_base_dimension, boost::units::static_rational< -2, 1 > >, boost::units::dimensionless_type > > >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            MechanicalStimulusCalculator3_exposer.def( 
                "SetTauP"
                , SetTauP_function_type( &::MechanicalStimulusCalculator< 3 >::SetTauP )
                , ( bp::arg("tauP") ) );
        
        }
        { //::MechanicalStimulusCalculator< 3 >::SetTauRef
        
            typedef MechanicalStimulusCalculator< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetTauRef_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< -1, 1 > >, boost::units::list< boost::units::dim< boost::units::mass_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::list< boost::units::dim< boost::units::time_base_dimension, boost::units::static_rational< -2, 1 > >, boost::units::dimensionless_type > > >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            MechanicalStimulusCalculator3_exposer.def( 
                "SetTauRef"
                , SetTauRef_function_type( &::MechanicalStimulusCalculator< 3 >::SetTauRef )
                , ( bp::arg("tauRef") ) );
        
        }
        MechanicalStimulusCalculator3_exposer.staticmethod( "Create" );
        bp::register_ptr_to_python< boost::shared_ptr< MechanicalStimulusCalculator<3> > >();
        bp::implicitly_convertible< boost::shared_ptr< MechanicalStimulusCalculator< 3 > >, boost::shared_ptr< AbstractVesselNetworkCalculator< 3 > > >();
    }

}
