#ifndef MetabolicStimulusCalculator3_hpp__pyplusplus_wrapper
#define MetabolicStimulusCalculator3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_MetabolicStimulusCalculator3_class(py::module &m);
#endif // MetabolicStimulusCalculator3_hpp__pyplusplus_wrapper
