#ifndef StructuralAdaptationSolver3_hpp__pyplusplus_wrapper
#define StructuralAdaptationSolver3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_StructuralAdaptationSolver3_class(py::module &m);
#endif // StructuralAdaptationSolver3_hpp__pyplusplus_wrapper
