#ifndef AbstractMicrovesselModifier3_hpp__pyplusplus_wrapper
#define AbstractMicrovesselModifier3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractMicrovesselModifier3_class(py::module &m);
#endif // AbstractMicrovesselModifier3_hpp__pyplusplus_wrapper
