#ifndef AbstractMicrovesselModifier2_hpp__pyplusplus_wrapper
#define AbstractMicrovesselModifier2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractMicrovesselModifier2_class(py::module &m);
#endif // AbstractMicrovesselModifier2_hpp__pyplusplus_wrapper
