#ifndef VtkSceneMicrovesselModifier2_hpp__pyplusplus_wrapper
#define VtkSceneMicrovesselModifier2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_VtkSceneMicrovesselModifier2_class(py::module &m);
#endif // VtkSceneMicrovesselModifier2_hpp__pyplusplus_wrapper
