// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "NetworkToSurface3.pypp.hpp"

namespace bp = boost::python;

void register_NetworkToSurface3_class(){

    { //::NetworkToSurface< 3 >
        typedef bp::class_< NetworkToSurface< 3 > > NetworkToSurface3_exposer_t;
        NetworkToSurface3_exposer_t NetworkToSurface3_exposer = NetworkToSurface3_exposer_t( "NetworkToSurface3", bp::init< >() );
        bp::scope NetworkToSurface3_scope( NetworkToSurface3_exposer );
        { //::NetworkToSurface< 3 >::Create
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef ::boost::shared_ptr< NetworkToSurface< 3 > > ( *Create_function_type )(  );
            
            NetworkToSurface3_exposer.def( 
                "Create"
                , Create_function_type( &::NetworkToSurface< 3 >::Create ) );
        
        }
        { //::NetworkToSurface< 3 >::GetNetworkToImageTool
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef ::boost::shared_ptr< NetworkToImage< 3 > > ( exported_class_t::*GetNetworkToImageTool_function_type)(  ) ;
            
            NetworkToSurface3_exposer.def( 
                "GetNetworkToImageTool"
                , GetNetworkToImageTool_function_type( &::NetworkToSurface< 3 >::GetNetworkToImageTool ) );
        
        }
        { //::NetworkToSurface< 3 >::GetSurface
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef ::vtkSmartPointer< vtkPolyData > ( exported_class_t::*GetSurface_function_type)(  ) ;
            
            NetworkToSurface3_exposer.def( 
                "GetSurface"
                , GetSurface_function_type( &::NetworkToSurface< 3 >::GetSurface ) );
        
        }
        { //::NetworkToSurface< 3 >::SetBandPassFrequency
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetBandPassFrequency_function_type)( double ) ;
            
            NetworkToSurface3_exposer.def( 
                "SetBandPassFrequency"
                , SetBandPassFrequency_function_type( &::NetworkToSurface< 3 >::SetBandPassFrequency )
                , ( bp::arg("bandPassFrequency") ) );
        
        }
        { //::NetworkToSurface< 3 >::SetDoSmoothing
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetDoSmoothing_function_type)( bool ) ;
            
            NetworkToSurface3_exposer.def( 
                "SetDoSmoothing"
                , SetDoSmoothing_function_type( &::NetworkToSurface< 3 >::SetDoSmoothing )
                , ( bp::arg("doSmoothing") ) );
        
        }
        { //::NetworkToSurface< 3 >::SetDoSurfaceRemeshing
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetDoSurfaceRemeshing_function_type)( bool ) ;
            
            NetworkToSurface3_exposer.def( 
                "SetDoSurfaceRemeshing"
                , SetDoSurfaceRemeshing_function_type( &::NetworkToSurface< 3 >::SetDoSurfaceRemeshing )
                , ( bp::arg("doRemeshing") ) );
        
        }
        { //::NetworkToSurface< 3 >::SetNumSmoothingIterations
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetNumSmoothingIterations_function_type)( unsigned int ) ;
            
            NetworkToSurface3_exposer.def( 
                "SetNumSmoothingIterations"
                , SetNumSmoothingIterations_function_type( &::NetworkToSurface< 3 >::SetNumSmoothingIterations )
                , ( bp::arg("numIterations") ) );
        
        }
        { //::NetworkToSurface< 3 >::SetRemeshingTargetEdgeLength
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetRemeshingTargetEdgeLength_function_type)( double ) ;
            
            NetworkToSurface3_exposer.def( 
                "SetRemeshingTargetEdgeLength"
                , SetRemeshingTargetEdgeLength_function_type( &::NetworkToSurface< 3 >::SetRemeshingTargetEdgeLength )
                , ( bp::arg("length") ) );
        
        }
        { //::NetworkToSurface< 3 >::SetResamplingSplineSize
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetResamplingSplineSize_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            NetworkToSurface3_exposer.def( 
                "SetResamplingSplineSize"
                , SetResamplingSplineSize_function_type( &::NetworkToSurface< 3 >::SetResamplingSplineSize )
                , ( bp::arg("splineResampleSize") ) );
        
        }
        { //::NetworkToSurface< 3 >::SetSmoothingFeatureAngle
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetSmoothingFeatureAngle_function_type)( double ) ;
            
            NetworkToSurface3_exposer.def( 
                "SetSmoothingFeatureAngle"
                , SetSmoothingFeatureAngle_function_type( &::NetworkToSurface< 3 >::SetSmoothingFeatureAngle )
                , ( bp::arg("featureAngle") ) );
        
        }
        { //::NetworkToSurface< 3 >::SetVesselNetwork
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetVesselNetwork_function_type)( ::boost::shared_ptr< VesselNetwork< 3 > > ) ;
            
            NetworkToSurface3_exposer.def( 
                "SetVesselNetwork"
                , SetVesselNetwork_function_type( &::NetworkToSurface< 3 >::SetVesselNetwork )
                , ( bp::arg("pNetwork") ) );
        
        }
        { //::NetworkToSurface< 3 >::Update
        
            typedef NetworkToSurface< 3 > exported_class_t;
            typedef void ( exported_class_t::*Update_function_type)(  ) ;
            
            NetworkToSurface3_exposer.def( 
                "Update"
                , Update_function_type( &::NetworkToSurface< 3 >::Update ) );
        
        }
        NetworkToSurface3_exposer.staticmethod( "Create" );
        bp::register_ptr_to_python< boost::shared_ptr< NetworkToSurface<3> > >();
    }

}
