// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "DiscreteContinuumMeshGenerator2_2.pypp.hpp"

namespace bp = boost::python;

void register_DiscreteContinuumMeshGenerator2_2_class(){

    { //::DiscreteContinuumMeshGenerator< 2, 2 >
        typedef bp::class_< DiscreteContinuumMeshGenerator< 2, 2 > > DiscreteContinuumMeshGenerator2_2_exposer_t;
        DiscreteContinuumMeshGenerator2_2_exposer_t DiscreteContinuumMeshGenerator2_2_exposer = DiscreteContinuumMeshGenerator2_2_exposer_t( "DiscreteContinuumMeshGenerator2_2", bp::init< >() );
        bp::scope DiscreteContinuumMeshGenerator2_2_scope( DiscreteContinuumMeshGenerator2_2_exposer );
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::Create
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef ::boost::shared_ptr< DiscreteContinuumMeshGenerator< 2, 2 > > ( *Create_function_type )(  );
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "Create"
                , Create_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::Create ) );
        
        }
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::GetMesh
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef ::boost::shared_ptr< DiscreteContinuumMesh< 2, 2 > > ( exported_class_t::*GetMesh_function_type)(  ) ;
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "GetMesh"
                , GetMesh_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::GetMesh ) );
        
        }
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::SetDomain
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef void ( exported_class_t::*SetDomain_function_type)( ::boost::shared_ptr< Part< 2 > > ) ;
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "SetDomain"
                , SetDomain_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::SetDomain )
                , ( bp::arg("pDomain") ) );
        
        }
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::SetDomain
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef void ( exported_class_t::*SetDomain_function_type)( ::vtkSmartPointer< vtkPolyData > ) ;
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "SetDomain"
                , SetDomain_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::SetDomain )
                , ( bp::arg("pDomain") ) );
        
        }
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::SetDomain
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef void ( exported_class_t::*SetDomain_function_type)( ::std::string const & ) ;
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "SetDomain"
                , SetDomain_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::SetDomain )
                , ( bp::arg("rPathToStl") ) );
        
        }
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::SetHoles
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef void ( exported_class_t::*SetHoles_function_type)( ::std::vector< DimensionalChastePoint<2> > ) ;
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "SetHoles"
                , SetHoles_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::SetHoles )
                , ( bp::arg("holes") ) );
        
        }
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::SetMaxElementArea
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef void ( exported_class_t::*SetMaxElementArea_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 3, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "SetMaxElementArea"
                , SetMaxElementArea_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::SetMaxElementArea )
                , ( bp::arg("maxElementArea") ) );
        
        }
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::SetRegionMarkers
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef void ( exported_class_t::*SetRegionMarkers_function_type)( ::std::vector< DimensionalChastePoint<2> > ) ;
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "SetRegionMarkers"
                , SetRegionMarkers_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::SetRegionMarkers )
                , ( bp::arg("regionMarkers") ) );
        
        }
        { //::DiscreteContinuumMeshGenerator< 2, 2 >::Update
        
            typedef DiscreteContinuumMeshGenerator< 2, 2 > exported_class_t;
            typedef void ( exported_class_t::*Update_function_type)(  ) ;
            
            DiscreteContinuumMeshGenerator2_2_exposer.def( 
                "Update"
                , Update_function_type( &::DiscreteContinuumMeshGenerator< 2, 2 >::Update ) );
        
        }
        DiscreteContinuumMeshGenerator2_2_exposer.staticmethod( "Create" );
        bp::register_ptr_to_python< boost::shared_ptr< DiscreteContinuumMeshGenerator<2, 2> > >();
    }

}
