#ifndef DiscreteContinuumMeshGenerator2_2_hpp__pyplusplus_wrapper
#define DiscreteContinuumMeshGenerator2_2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_DiscreteContinuumMeshGenerator2_2_class(py::module &m);
#endif // DiscreteContinuumMeshGenerator2_2_hpp__pyplusplus_wrapper
