#ifndef Owen11CellPopulationGenerator3_hpp__pyplusplus_wrapper
#define Owen11CellPopulationGenerator3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_Owen11CellPopulationGenerator3_class(py::module &m);
#endif // Owen11CellPopulationGenerator3_hpp__pyplusplus_wrapper
