#ifndef Owen2011OxygenBasedCellCycleModel_hpp__pyplusplus_wrapper
#define Owen2011OxygenBasedCellCycleModel_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_Owen2011OxygenBasedCellCycleModel_class(py::module &m);
#endif // Owen2011OxygenBasedCellCycleModel_hpp__pyplusplus_wrapper
