#ifndef QuiescentCancerCellMutationState_hpp__pyplusplus_wrapper
#define QuiescentCancerCellMutationState_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_QuiescentCancerCellMutationState_class(py::module &m);
#endif // QuiescentCancerCellMutationState_hpp__pyplusplus_wrapper
