#ifndef AbstractMixedGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper
#define AbstractMixedGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractMixedGridDiscreteContinuumSolver3_class(py::module &m);
#endif // AbstractMixedGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper
