#ifndef AbstractUnstructuredGridDiscreteContinuumSolver2_hpp__pyplusplus_wrapper
#define AbstractUnstructuredGridDiscreteContinuumSolver2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractUnstructuredGridDiscreteContinuumSolver2_class(py::module &m);
#endif // AbstractUnstructuredGridDiscreteContinuumSolver2_hpp__pyplusplus_wrapper
