#ifndef AbstractDiscreteContinuumParabolicPde3_3_hpp__pyplusplus_wrapper
#define AbstractDiscreteContinuumParabolicPde3_3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractDiscreteContinuumParabolicPde3_3_class(py::module &m);
#endif // AbstractDiscreteContinuumParabolicPde3_3_hpp__pyplusplus_wrapper
