#ifndef AbstractUnstructuredGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper
#define AbstractUnstructuredGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractUnstructuredGridDiscreteContinuumSolver3_class(py::module &m);
#endif // AbstractUnstructuredGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper
