#ifndef AbstractDiscreteContinuumSolver2_hpp__pyplusplus_wrapper
#define AbstractDiscreteContinuumSolver2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractDiscreteContinuumSolver2_class(py::module &m);
#endif // AbstractDiscreteContinuumSolver2_hpp__pyplusplus_wrapper
