#ifndef AbstractDiscreteContinuumLinearEllipticPde3_3_hpp__pyplusplus_wrapper
#define AbstractDiscreteContinuumLinearEllipticPde3_3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractDiscreteContinuumLinearEllipticPde3_3_class(py::module &m);
#endif // AbstractDiscreteContinuumLinearEllipticPde3_3_hpp__pyplusplus_wrapper
