// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "AbstractDiscreteContinuumPde3_3.pypp.hpp"

namespace bp = boost::python;

struct AbstractDiscreteContinuumPde_less__3_comma__3__greater__wrapper : AbstractDiscreteContinuumPde< 3, 3 >, bp::wrapper< AbstractDiscreteContinuumPde< 3, 3 > > {

    AbstractDiscreteContinuumPde_less__3_comma__3__greater__wrapper(AbstractDiscreteContinuumPde<3, 3> const & arg )
    : AbstractDiscreteContinuumPde<3, 3>( arg )
      , bp::wrapper< AbstractDiscreteContinuumPde< 3, 3 > >(){
        // copy constructor
        
    }

    AbstractDiscreteContinuumPde_less__3_comma__3__greater__wrapper( )
    : AbstractDiscreteContinuumPde<3, 3>( )
      , bp::wrapper< AbstractDiscreteContinuumPde< 3, 3 > >(){
        // null constructor
    
    }

    virtual void UpdateDiscreteSourceStrengths(  ) {
        if( bp::override func_UpdateDiscreteSourceStrengths = this->get_override( "UpdateDiscreteSourceStrengths" ) )
            func_UpdateDiscreteSourceStrengths(  );
        else{
            this->AbstractDiscreteContinuumPde< 3, 3 >::UpdateDiscreteSourceStrengths(  );
        }
    }
    
    void default_UpdateDiscreteSourceStrengths(  ) {
        AbstractDiscreteContinuumPde< 3, 3 >::UpdateDiscreteSourceStrengths( );
    }

};

void register_AbstractDiscreteContinuumPde3_3_class(){

    { //::AbstractDiscreteContinuumPde< 3, 3 >
        typedef bp::class_< AbstractDiscreteContinuumPde_less__3_comma__3__greater__wrapper > AbstractDiscreteContinuumPde3_3_exposer_t;
        AbstractDiscreteContinuumPde3_3_exposer_t AbstractDiscreteContinuumPde3_3_exposer = AbstractDiscreteContinuumPde3_3_exposer_t( "AbstractDiscreteContinuumPde3_3", bp::init< >() );
        bp::scope AbstractDiscreteContinuumPde3_3_scope( AbstractDiscreteContinuumPde3_3_exposer );
        { //::AbstractDiscreteContinuumPde< 3, 3 >::AddDiscreteSource
        
            typedef AbstractDiscreteContinuumPde< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*AddDiscreteSource_function_type)( ::boost::shared_ptr< DiscreteSource< 3 > > ) ;
            
            AbstractDiscreteContinuumPde3_3_exposer.def( 
                "AddDiscreteSource"
                , AddDiscreteSource_function_type( &::AbstractDiscreteContinuumPde< 3, 3 >::AddDiscreteSource )
                , ( bp::arg("pDiscreteSource") ) );
        
        }
        { //::AbstractDiscreteContinuumPde< 3, 3 >::ComputeIsotropicDiffusionTerm
        
            typedef AbstractDiscreteContinuumPde< 3, 3 > exported_class_t;
            typedef ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 2, 1 > >, boost::units::list< boost::units::dim< boost::units::time_base_dimension, boost::units::static_rational< -1, 1 > >, boost::units::dimensionless_type > >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ( exported_class_t::*ComputeIsotropicDiffusionTerm_function_type)(  ) ;
            
            AbstractDiscreteContinuumPde3_3_exposer.def( 
                "ComputeIsotropicDiffusionTerm"
                , ComputeIsotropicDiffusionTerm_function_type( &::AbstractDiscreteContinuumPde< 3, 3 >::ComputeIsotropicDiffusionTerm ) );
        
        }
        { //::AbstractDiscreteContinuumPde< 3, 3 >::GetDiscreteSources
        
            typedef AbstractDiscreteContinuumPde< 3, 3 > exported_class_t;
            typedef ::std::vector< boost::shared_ptr<DiscreteSource<3> > > ( exported_class_t::*GetDiscreteSources_function_type)(  ) ;
            
            AbstractDiscreteContinuumPde3_3_exposer.def( 
                "GetDiscreteSources"
                , GetDiscreteSources_function_type( &::AbstractDiscreteContinuumPde< 3, 3 >::GetDiscreteSources ) );
        
        }
        { //::AbstractDiscreteContinuumPde< 3, 3 >::SetIsotropicDiffusionConstant
        
            typedef AbstractDiscreteContinuumPde< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*SetIsotropicDiffusionConstant_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 2, 1 > >, boost::units::list< boost::units::dim< boost::units::time_base_dimension, boost::units::static_rational< -1, 1 > >, boost::units::dimensionless_type > >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            AbstractDiscreteContinuumPde3_3_exposer.def( 
                "SetIsotropicDiffusionConstant"
                , SetIsotropicDiffusionConstant_function_type( &::AbstractDiscreteContinuumPde< 3, 3 >::SetIsotropicDiffusionConstant )
                , ( bp::arg("diffusivity") ) );
        
        }
        { //::AbstractDiscreteContinuumPde< 3, 3 >::SetReferenceConcentration
        
            typedef AbstractDiscreteContinuumPde< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*SetReferenceConcentration_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< -3, 1 > >, boost::units::list< boost::units::dim< boost::units::amount_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type > >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            AbstractDiscreteContinuumPde3_3_exposer.def( 
                "SetReferenceConcentration"
                , SetReferenceConcentration_function_type( &::AbstractDiscreteContinuumPde< 3, 3 >::SetReferenceConcentration )
                , ( bp::arg("referenceConcentration") ) );
        
        }
        { //::AbstractDiscreteContinuumPde< 3, 3 >::SetReferenceLength
        
            typedef AbstractDiscreteContinuumPde< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*SetReferenceLength_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            AbstractDiscreteContinuumPde3_3_exposer.def( 
                "SetReferenceLength"
                , SetReferenceLength_function_type( &::AbstractDiscreteContinuumPde< 3, 3 >::SetReferenceLength )
                , ( bp::arg("referenceLength") ) );
        
        }
        { //::AbstractDiscreteContinuumPde< 3, 3 >::SetReferenceTime
        
            typedef AbstractDiscreteContinuumPde< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*SetReferenceTime_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::time_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            AbstractDiscreteContinuumPde3_3_exposer.def( 
                "SetReferenceTime"
                , SetReferenceTime_function_type( &::AbstractDiscreteContinuumPde< 3, 3 >::SetReferenceTime )
                , ( bp::arg("referenceTime") ) );
        
        }
        { //::AbstractDiscreteContinuumPde< 3, 3 >::UpdateDiscreteSourceStrengths
        
            typedef AbstractDiscreteContinuumPde< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*UpdateDiscreteSourceStrengths_function_type)(  ) ;
            typedef void ( AbstractDiscreteContinuumPde_less__3_comma__3__greater__wrapper::*default_UpdateDiscreteSourceStrengths_function_type)(  ) ;
            
            AbstractDiscreteContinuumPde3_3_exposer.def( 
                "UpdateDiscreteSourceStrengths"
                , UpdateDiscreteSourceStrengths_function_type(&::AbstractDiscreteContinuumPde< 3, 3 >::UpdateDiscreteSourceStrengths)
                , default_UpdateDiscreteSourceStrengths_function_type(&AbstractDiscreteContinuumPde_less__3_comma__3__greater__wrapper::default_UpdateDiscreteSourceStrengths) );
        
        }
        bp::register_ptr_to_python< boost::shared_ptr< AbstractDiscreteContinuumPde<3, 3> > >();
    }

}
