#ifndef AbstractFiniteElementSolverBase2_hpp__pyplusplus_wrapper
#define AbstractFiniteElementSolverBase2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractFiniteElementSolverBase2_class(py::module &m);
#endif // AbstractFiniteElementSolverBase2_hpp__pyplusplus_wrapper
