#ifndef AbstractFiniteDifferenceSolverBase2_hpp__pyplusplus_wrapper
#define AbstractFiniteDifferenceSolverBase2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractFiniteDifferenceSolverBase2_class(py::module &m);
#endif // AbstractFiniteDifferenceSolverBase2_hpp__pyplusplus_wrapper
