#ifndef AbstractRegularGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper
#define AbstractRegularGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractRegularGridDiscreteContinuumSolver3_class(py::module &m);
#endif // AbstractRegularGridDiscreteContinuumSolver3_hpp__pyplusplus_wrapper
