#ifndef AbstractRegularGridDiscreteContinuumSolver2_hpp__pyplusplus_wrapper
#define AbstractRegularGridDiscreteContinuumSolver2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractRegularGridDiscreteContinuumSolver2_class(py::module &m);
#endif // AbstractRegularGridDiscreteContinuumSolver2_hpp__pyplusplus_wrapper
