#ifndef AbstractDiscreteContinuumPde3_3_hpp__pyplusplus_wrapper
#define AbstractDiscreteContinuumPde3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractDiscreteContinuumPde3_3_class(py::module &m);
#endif // AbstractDiscreteContinuumPde3_3_hpp__pyplusplus_wrapper
