#ifndef CoupledLumpedSystemFiniteElementSolver2_hpp__pyplusplus_wrapper
#define CoupledLumpedSystemFiniteElementSolver2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_CoupledLumpedSystemFiniteElementSolver2_class(py::module &m);
#endif // CoupledLumpedSystemFiniteElementSolver2_hpp__pyplusplus_wrapper
