#ifndef CoupledLumpedSystemFiniteElementSolver3_hpp__pyplusplus_wrapper
#define CoupledLumpedSystemFiniteElementSolver3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CoupledLumpedSystemFiniteElementSolver3_class(py::module &m);
#endif // CoupledLumpedSystemFiniteElementSolver3_hpp__pyplusplus_wrapper
