#ifndef CoupledVegfPelletDiffusionReactionPde2_2_hpp__pyplusplus_wrapper
#define CoupledVegfPelletDiffusionReactionPde2_2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_CoupledVegfPelletDiffusionReactionPde2_2_class(py::module &m);
#endif // CoupledVegfPelletDiffusionReactionPde2_2_hpp__pyplusplus_wrapper
