#ifndef CoupledLumpedSystemFiniteDifferenceSolver2_hpp__pyplusplus_wrapper
#define CoupledLumpedSystemFiniteDifferenceSolver2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_CoupledLumpedSystemFiniteDifferenceSolver2_class(py::module &m);
#endif // CoupledLumpedSystemFiniteDifferenceSolver2_hpp__pyplusplus_wrapper
