#ifndef DiscreteContinuumBoundaryCondition2_hpp__pyplusplus_wrapper
#define DiscreteContinuumBoundaryCondition2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_DiscreteContinuumBoundaryCondition2_class(py::module &m);
#endif // DiscreteContinuumBoundaryCondition2_hpp__pyplusplus_wrapper
