#ifndef DiscreteContinuumBoundaryCondition3_hpp__pyplusplus_wrapper
#define DiscreteContinuumBoundaryCondition3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_DiscreteContinuumBoundaryCondition3_class(py::module &m);
#endif // DiscreteContinuumBoundaryCondition3_hpp__pyplusplus_wrapper
