#ifndef DiscreteContinuumLinearEllipticPde3_3_hpp__pyplusplus_wrapper
#define DiscreteContinuumLinearEllipticPde3_3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_DiscreteContinuumLinearEllipticPde3_3_class(py::module &m);
#endif // DiscreteContinuumLinearEllipticPde3_3_hpp__pyplusplus_wrapper
