#ifndef SimpleLinearEllipticFiniteDifferenceSolver3_hpp__pyplusplus_wrapper
#define SimpleLinearEllipticFiniteDifferenceSolver3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_SimpleLinearEllipticFiniteDifferenceSolver3_class(py::module &m);
#endif // SimpleLinearEllipticFiniteDifferenceSolver3_hpp__pyplusplus_wrapper
