#ifndef SimpleParabolicFiniteElementSolver3_hpp__pyplusplus_wrapper
#define SimpleParabolicFiniteElementSolver3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_SimpleParabolicFiniteElementSolver3_class(py::module &m);
#endif // SimpleParabolicFiniteElementSolver3_hpp__pyplusplus_wrapper
