#ifndef SimpleNonLinearEllipticFiniteElementSolver3_hpp__pyplusplus_wrapper
#define SimpleNonLinearEllipticFiniteElementSolver3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_SimpleNonLinearEllipticFiniteElementSolver3_class(py::module &m);
#endif // SimpleNonLinearEllipticFiniteElementSolver3_hpp__pyplusplus_wrapper
