#ifndef SimpleNonLinearEllipticFiniteDifferenceSolver3_hpp__pyplusplus_wrapper
#define SimpleNonLinearEllipticFiniteDifferenceSolver3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_SimpleNonLinearEllipticFiniteDifferenceSolver3_class(py::module &m);
#endif // SimpleNonLinearEllipticFiniteDifferenceSolver3_hpp__pyplusplus_wrapper
