#ifndef SimpleNonLinearEllipticFiniteDifferenceSolver2_hpp__pyplusplus_wrapper
#define SimpleNonLinearEllipticFiniteDifferenceSolver2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_SimpleNonLinearEllipticFiniteDifferenceSolver2_class(py::module &m);
#endif // SimpleNonLinearEllipticFiniteDifferenceSolver2_hpp__pyplusplus_wrapper
