#ifndef SimpleLinearEllipticFiniteElementSolver3_hpp__pyplusplus_wrapper
#define SimpleLinearEllipticFiniteElementSolver3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_SimpleLinearEllipticFiniteElementSolver3_class(py::module &m);
#endif // SimpleLinearEllipticFiniteElementSolver3_hpp__pyplusplus_wrapper
