#ifndef SolutionDependentDiscreteSource2_hpp__pyplusplus_wrapper
#define SolutionDependentDiscreteSource2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_SolutionDependentDiscreteSource2_class(py::module &m);
#endif // SolutionDependentDiscreteSource2_hpp__pyplusplus_wrapper
